/* exceptions.c generated by valac 0.34.8, the Vala compiler
 * generated from exceptions.gs, do not modify */


#include <glib.h>
#include <glib-object.h>


typedef enum  {
	SDX_SDL_EXCEPTION_Initialization,
	SDX_SDL_EXCEPTION_ImageInitialization,
	SDX_SDL_EXCEPTION_TtfInitialization,
	SDX_SDL_EXCEPTION_TextureFilteringNotEnabled,
	SDX_SDL_EXCEPTION_OpenWindow,
	SDX_SDL_EXCEPTION_CreateRenderer,
	SDX_SDL_EXCEPTION_InvalidForPlatform,
	SDX_SDL_EXCEPTION_UnableToLoadResource,
	SDX_SDL_EXCEPTION_NullPointer,
	SDX_SDL_EXCEPTION_NoSuchElement
} sdxSdlException;
#define SDX_SDL_EXCEPTION sdx_sdl_exception_quark ()


GQuark sdx_sdl_exception_quark (void);


GQuark sdx_sdl_exception_quark (void) {
	return g_quark_from_static_string ("sdx_sdl_exception-quark");
}



