/* Files.c generated by valac 0.34.8, the Vala compiler
 * generated from Files.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define SDX_TYPE_FILE_TYPE (sdx_file_type_get_type ())
typedef struct _sdxFiles sdxFiles;
#define _g_free0(var) (var = (g_free (var), NULL))

typedef enum  {
	SDX_FILE_TYPE_Parent,
	SDX_FILE_TYPE_Resource,
	SDX_FILE_TYPE_Asset,
	SDX_FILE_TYPE_Absolute,
	SDX_FILE_TYPE_Relative
} sdxFileType;

struct _sdxFiles {
	gint _retainCount;
	gboolean isResource;
	gchar* resourcePath;
};



GType sdx_file_type_get_type (void) G_GNUC_CONST;
void sdx_files_free (sdxFiles* self);
static void sdx_files_instance_init (sdxFiles * self);
sdxFiles* sdx_files_retain (sdxFiles* self);
void sdx_files_release (sdxFiles* self);
void sdx_files_free (sdxFiles* self);
sdxFiles* sdx_files_new (const gchar* resourcePath);


GType sdx_file_type_get_type (void) {
	static volatile gsize sdx_file_type_type_id__volatile = 0;
	if (g_once_init_enter (&sdx_file_type_type_id__volatile)) {
		static const GEnumValue values[] = {{SDX_FILE_TYPE_Parent, "SDX_FILE_TYPE_Parent", "parent"}, {SDX_FILE_TYPE_Resource, "SDX_FILE_TYPE_Resource", "resource"}, {SDX_FILE_TYPE_Asset, "SDX_FILE_TYPE_Asset", "asset"}, {SDX_FILE_TYPE_Absolute, "SDX_FILE_TYPE_Absolute", "absolute"}, {SDX_FILE_TYPE_Relative, "SDX_FILE_TYPE_Relative", "relative"}, {0, NULL, NULL}};
		GType sdx_file_type_type_id;
		sdx_file_type_type_id = g_enum_register_static ("sdxFileType", values);
		g_once_init_leave (&sdx_file_type_type_id__volatile, sdx_file_type_type_id);
	}
	return sdx_file_type_type_id__volatile;
}


sdxFiles* sdx_files_retain (sdxFiles* self) {
	sdxFiles* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_atomic_int_add ((volatile gint *) (&self->_retainCount), 1);
	result = self;
	return result;
}


void sdx_files_release (sdxFiles* self) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_atomic_int_dec_and_test ((volatile gint *) (&self->_retainCount));
	if (_tmp0_) {
		sdx_files_free (self);
	}
}


sdxFiles* sdx_files_new (const gchar* resourcePath) {
	sdxFiles* self;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (resourcePath != NULL, NULL);
	self = g_slice_new0 (sdxFiles);
	sdx_files_instance_init (self);
	_tmp0_ = resourcePath;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->resourcePath);
	self->resourcePath = _tmp1_;
	return self;
}


static void sdx_files_instance_init (sdxFiles * self) {
	self->_retainCount = 1;
}


void sdx_files_free (sdxFiles* self) {
	_g_free0 (self->resourcePath);
	g_slice_free (sdxFiles, self);
}



