/* main.c generated by valac 0.34.8, the Vala compiler
 * generated from main.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL.h>
#include <SDL2/SDL_video.h>
#include <SDL2/SDL_rect.h>

#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Game Game;
void game_release (Game* self);
void game_free (Game* self);
Game* game_retain (Game* self);
#define _game_release0(var) ((var == NULL) ? NULL : (var = (game_release (var), NULL)))
#define _SDL_DestroyWindow0(var) ((var == NULL) ? NULL : (var = (SDL_DestroyWindow (var), NULL)))

typedef enum  {
	EXCEPTION_SDLException,
	EXCEPTION_InvalidValue,
	EXCEPTION_MapFileFormat
} Exception;
#define EXCEPTION exception_quark ()

extern gdouble startTime;
gdouble startTime = 0.0;
extern gint lastTick;
gint lastTick = 0;
extern gboolean sdx_running;

GQuark exception_quark (void);
gchar* formatTime (gint ticks);
void sdlFailIf (gboolean cond, const gchar* reason);
void _vala_main (gchar** args, int args_length1);
SDL_Window* sdx_initialize (gint width, gint height, const gchar* name);
void game_free (Game* self);
Game* game_new (void);
gdouble sdx_getNow (void);
void sdx_start (void);
void sdx_processEvents (void);
void game_update (Game* self, gint tick);
void game_render (Game* self, gint tick);

extern const SDL_Point WINDOW_SIZE;

GQuark exception_quark (void) {
	return g_quark_from_static_string ("exception-quark");
}


inline gchar* formatTime (gint ticks) {
	gchar* result = NULL;
	gint mins = 0;
	gint _tmp0_ = 0;
	gint secs = 0;
	gint _tmp1_ = 0;
	gchar* _tmp2_ = NULL;
	_tmp0_ = ticks;
	mins = (_tmp0_ / 50) / 60;
	_tmp1_ = ticks;
	secs = (_tmp1_ / 50) % 60;
	_tmp2_ = g_strdup_printf ("%02d:%02d", (gint) mins, (gint) secs);
	result = _tmp2_;
	return result;
}


inline void sdlFailIf (gboolean cond, const gchar* reason) {
	gboolean _tmp0_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_if_fail (reason != NULL);
	_tmp0_ = cond;
	if (_tmp0_) {
		const gchar* _tmp1_ = NULL;
		gchar* _tmp2_ = NULL;
		gchar* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		GError* _tmp7_ = NULL;
		GError* _tmp8_ = NULL;
		_tmp1_ = reason;
		_tmp2_ = g_strconcat (_tmp1_, ", SDL error: ", NULL);
		_tmp3_ = _tmp2_;
		_tmp4_ = SDL_GetError ();
		_tmp5_ = g_strconcat (_tmp3_, _tmp4_, NULL);
		_tmp6_ = _tmp5_;
		_tmp7_ = g_error_new_literal (EXCEPTION, EXCEPTION_SDLException, _tmp6_);
		_tmp8_ = _tmp7_;
		_g_free0 (_tmp6_);
		_g_free0 (_tmp3_);
		_inner_error_ = _tmp8_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


void _vala_main (gchar** args, int args_length1) {
	SDL_Window* window = NULL;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	SDL_Window* _tmp2_ = NULL;
	Game* game = NULL;
	Game* _tmp3_ = NULL;
	gdouble _tmp4_ = 0.0;
	_tmp0_ = WINDOW_SIZE.x;
	_tmp1_ = WINDOW_SIZE.y;
	_tmp2_ = sdx_initialize ((gint) _tmp0_, (gint) _tmp1_, "Shmupwarz");
	window = _tmp2_;
	_tmp3_ = game_new ();
	game = _tmp3_;
	_tmp4_ = sdx_getNow ();
	startTime = _tmp4_;
	lastTick = 0;
	sdx_start ();
	while (TRUE) {
		gboolean _tmp5_ = FALSE;
		gint newTick = 0;
		gdouble _tmp6_ = 0.0;
		gdouble _tmp7_ = 0.0;
		gint _tmp14_ = 0;
		Game* _tmp15_ = NULL;
		gint _tmp16_ = 0;
		_tmp5_ = sdx_running;
		if (!_tmp5_) {
			break;
		}
		sdx_processEvents ();
		_tmp6_ = sdx_getNow ();
		_tmp7_ = startTime;
		newTick = (gint) ((_tmp6_ - _tmp7_) * 50);
		{
			gint tick = 0;
			gint _tmp8_ = 0;
			_tmp8_ = lastTick;
			tick = _tmp8_ + 1;
			{
				gboolean _tmp9_ = FALSE;
				_tmp9_ = TRUE;
				while (TRUE) {
					gint _tmp11_ = 0;
					Game* _tmp12_ = NULL;
					gint _tmp13_ = 0;
					if (!_tmp9_) {
						gint _tmp10_ = 0;
						_tmp10_ = tick;
						tick = _tmp10_ + 1;
					}
					_tmp9_ = FALSE;
					_tmp11_ = newTick;
					if (!(tick <= _tmp11_)) {
						break;
					}
					_tmp12_ = game;
					_tmp13_ = tick;
					game_update (_tmp12_, _tmp13_);
				}
			}
		}
		_tmp14_ = newTick;
		lastTick = _tmp14_;
		_tmp15_ = game;
		_tmp16_ = lastTick;
		game_render (_tmp15_, _tmp16_);
	}
	_game_release0 (game);
	_SDL_DestroyWindow0 (window);
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	_vala_main (argv, argc);
	return 0;
}



