/* Sound.c generated by valac 0.34.8, the Vala compiler
 * generated from Sound.vala, do not modify */


#include <glib.h>
#include <glib-object.h>

typedef struct _sdxaudioSound sdxaudioSound;
typedef struct _sdxfilesFileHandle sdxfilesFileHandle;

struct _sdxaudioSound {
	gint _retainCount;
};



void sdx_audio_sound_free (sdxaudioSound* self);
static void sdx_audio_sound_instance_init (sdxaudioSound * self);
sdxaudioSound* sdx_audio_sound_retain (sdxaudioSound* self);
void sdx_audio_sound_release (sdxaudioSound* self);
void sdx_audio_sound_free (sdxaudioSound* self);
void sdx_files_file_handle_free (sdxfilesFileHandle* self);
sdxaudioSound* sdx_audio_sound_new (sdxfilesFileHandle* file);
void sdx_audio_sound_play (sdxaudioSound* self, gint loops);


sdxaudioSound* sdx_audio_sound_retain (sdxaudioSound* self) {
	sdxaudioSound* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_atomic_int_add ((volatile gint *) (&self->_retainCount), 1);
	result = self;
	return result;
}


void sdx_audio_sound_release (sdxaudioSound* self) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_atomic_int_dec_and_test ((volatile gint *) (&self->_retainCount));
	if (_tmp0_) {
		sdx_audio_sound_free (self);
	}
}


sdxaudioSound* sdx_audio_sound_new (sdxfilesFileHandle* file) {
	sdxaudioSound* self;
	g_return_val_if_fail (file != NULL, NULL);
	self = g_slice_new0 (sdxaudioSound);
	sdx_audio_sound_instance_init (self);
	return self;
}


void sdx_audio_sound_play (sdxaudioSound* self, gint loops) {
	g_return_if_fail (self != NULL);
}


static void sdx_audio_sound_instance_init (sdxaudioSound * self) {
	self->_retainCount = 1;
}


void sdx_audio_sound_free (sdxaudioSound* self) {
	g_slice_free (sdxaudioSound, self);
}



