/* BitmapFont.c generated by valac 0.34.8, the Vala compiler
 * generated from BitmapFont.vala, do not modify */

/**
 * BitmapFont.gs
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>

typedef struct _sdxgraphicsBitmapFont sdxgraphicsBitmapFont;
typedef struct _sdxutilsJson sdxutilsJson;
typedef struct _sdxgraphicsTextureRegion sdxgraphicsTextureRegion;
typedef struct _sdxgraphicsBitmapFontData sdxgraphicsBitmapFontData;
void sdx_utils_json_release (sdxutilsJson* self);
void sdx_utils_json_free (sdxutilsJson* self);
sdxutilsJson* sdx_utils_json_retain (sdxutilsJson* self);
void sdx_utils_json_release (sdxutilsJson* self);
void sdx_utils_json_free (sdxutilsJson* self);
sdxutilsJson* sdx_utils_json_retain (sdxutilsJson* self);
#define _sdx_utils_json_release0(var) ((var == NULL) ? NULL : (var = (sdx_utils_json_release (var), NULL)))
void sdx_graphics_texture_region_release (sdxgraphicsTextureRegion* self);
void sdx_graphics_texture_region_free (sdxgraphicsTextureRegion* self);
sdxgraphicsTextureRegion* sdx_graphics_texture_region_retain (sdxgraphicsTextureRegion* self);
void sdx_graphics_texture_region_release (sdxgraphicsTextureRegion* self);
void sdx_graphics_texture_region_free (sdxgraphicsTextureRegion* self);
sdxgraphicsTextureRegion* sdx_graphics_texture_region_retain (sdxgraphicsTextureRegion* self);
#define _sdx_graphics_texture_region_release0(var) ((var == NULL) ? NULL : (var = (sdx_graphics_texture_region_release (var), NULL)))
void sdx_graphics_bitmap_font_data_release (sdxgraphicsBitmapFontData* self);
void sdx_graphics_bitmap_font_data_free (sdxgraphicsBitmapFontData* self);
sdxgraphicsBitmapFontData* sdx_graphics_bitmap_font_data_retain (sdxgraphicsBitmapFontData* self);
void sdx_graphics_bitmap_font_data_release (sdxgraphicsBitmapFontData* self);
void sdx_graphics_bitmap_font_data_free (sdxgraphicsBitmapFontData* self);
sdxgraphicsBitmapFontData* sdx_graphics_bitmap_font_data_retain (sdxgraphicsBitmapFontData* self);
#define _sdx_graphics_bitmap_font_data_release0(var) ((var == NULL) ? NULL : (var = (sdx_graphics_bitmap_font_data_release (var), NULL)))
#define __g_list_free__sdx_graphics_texture_region_release0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__sdx_graphics_texture_region_release0_ (var), NULL)))
typedef struct _sdxgraphicsGlyph sdxgraphicsGlyph;
typedef struct _sdxfilesFileHandle sdxfilesFileHandle;
void sdx_files_file_handle_release (sdxfilesFileHandle* self);
void sdx_files_file_handle_free (sdxfilesFileHandle* self);
sdxfilesFileHandle* sdx_files_file_handle_retain (sdxfilesFileHandle* self);
void sdx_files_file_handle_release (sdxfilesFileHandle* self);
void sdx_files_file_handle_free (sdxfilesFileHandle* self);
sdxfilesFileHandle* sdx_files_file_handle_retain (sdxfilesFileHandle* self);
#define _sdx_files_file_handle_release0(var) ((var == NULL) ? NULL : (var = (sdx_files_file_handle_release (var), NULL)))
void sdx_graphics_glyph_release (sdxgraphicsGlyph* self);
void sdx_graphics_glyph_free (sdxgraphicsGlyph* self);
sdxgraphicsGlyph* sdx_graphics_glyph_retain (sdxgraphicsGlyph* self);
void sdx_graphics_glyph_release (sdxgraphicsGlyph* self);
void sdx_graphics_glyph_free (sdxgraphicsGlyph* self);
sdxgraphicsGlyph* sdx_graphics_glyph_retain (sdxgraphicsGlyph* self);
#define _sdx_graphics_glyph_release0(var) ((var == NULL) ? NULL : (var = (sdx_graphics_glyph_release (var), NULL)))
typedef struct _sdxutilsJsVariant sdxutilsJsVariant;
#define _g_free0(var) (var = (g_free (var), NULL))

#define SDX_UTILS_TYPE_JS_TYPE (sdx_utils_js_type_get_type ())
void sdx_utils_js_variant_release (sdxutilsJsVariant* self);
void sdx_utils_js_variant_free (sdxutilsJsVariant* self);
sdxutilsJsVariant* sdx_utils_js_variant_retain (sdxutilsJsVariant* self);
void sdx_utils_js_variant_release (sdxutilsJsVariant* self);
void sdx_utils_js_variant_free (sdxutilsJsVariant* self);
sdxutilsJsVariant* sdx_utils_js_variant_retain (sdxutilsJsVariant* self);
#define _sdx_utils_js_variant_release0(var) ((var == NULL) ? NULL : (var = (sdx_utils_js_variant_release (var), NULL)))
typedef struct _sdxgraphicsSurface sdxgraphicsSurface;
typedef sdxgraphicsSurface sdxgraphicsSurfaceTextureSurface;
void sdx_graphics_surface_release (sdxgraphicsSurface* self);
void sdx_graphics_surface_free (sdxgraphicsSurface* self);
sdxgraphicsSurface* sdx_graphics_surface_retain (sdxgraphicsSurface* self);
void sdx_graphics_surface_release (sdxgraphicsSurface* self);
void sdx_graphics_surface_free (sdxgraphicsSurface* self);
sdxgraphicsSurface* sdx_graphics_surface_retain (sdxgraphicsSurface* self);
#define _sdx_graphics_surface_release0(var) ((var == NULL) ? NULL : (var = (sdx_graphics_surface_release (var), NULL)))

struct _sdxgraphicsBitmapFont {
	gint _retainCount;
	sdxutilsJson* dummy2;
	sdxgraphicsTextureRegion* dummy;
	sdxgraphicsBitmapFontData* data;
	GList* regions;
};

struct _sdxgraphicsGlyph {
	gint _retainCount;
	gint id;
	gint x;
	gint y;
	gint width;
	gint height;
	gdouble u;
	gdouble v;
	gdouble u2;
	gdouble v2;
	gint xoffset;
	gint yoffset;
	gint xadvance;
	gchar* kerning;
	gint kerning_length1;
	gint kerning_length2;
	gboolean fixedWidth;
	gint page;
};

struct _sdxgraphicsBitmapFontData {
	gint _retainCount;
	gchar** imagePaths;
	gint imagePaths_length1;
	sdxfilesFileHandle* fontFile;
	gboolean flipped;
	gdouble padTop;
	gdouble padRight;
	gdouble padBottom;
	gdouble padLeft;
	gdouble lineHeight;
	gdouble capHeight;
	gdouble ascent;
	gdouble descent;
	gdouble down;
	gdouble blankLineScale;
	gdouble scaleX;
	gdouble scaleY;
	gboolean markupEnabled;
	gdouble cursorX;
	sdxgraphicsGlyph** glyphs;
	gint glyphs_length1;
	gint glyphs_length2;
	sdxgraphicsGlyph* missingGlyph;
	gdouble spaceWidth;
	gdouble xHeight;
	gchar* breakChars;
	gint breakChars_length1;
	gchar* xChars;
	gint xChars_length1;
	gchar* capChars;
	gint capChars_length1;
};

typedef enum  {
	SDX_SDL_EXCEPTION_Initialization,
	SDX_SDL_EXCEPTION_ImageInitialization,
	SDX_SDL_EXCEPTION_TtfInitialization,
	SDX_SDL_EXCEPTION_TextureFilteringNotEnabled,
	SDX_SDL_EXCEPTION_OpenWindow,
	SDX_SDL_EXCEPTION_CreateRenderer,
	SDX_SDL_EXCEPTION_InvalidForPlatform,
	SDX_SDL_EXCEPTION_UnableToLoadResource,
	SDX_SDL_EXCEPTION_UnableToLoadSurface,
	SDX_SDL_EXCEPTION_UnableToLoadTexture,
	SDX_SDL_EXCEPTION_NullPointer,
	SDX_SDL_EXCEPTION_NoSuchElement,
	SDX_SDL_EXCEPTION_IllegalStateException,
	SDX_SDL_EXCEPTION_RuntimeException,
	SDX_SDL_EXCEPTION_NotReached
} sdxSdlException;
#define SDX_SDL_EXCEPTION sdx_sdl_exception_quark ()
typedef enum  {
	SDX_UTILS_JS_TYPE_JS_INVALID,
	SDX_UTILS_JS_TYPE_JS_BOOLEAN,
	SDX_UTILS_JS_TYPE_JS_NUMBER,
	SDX_UTILS_JS_TYPE_JS_STRING,
	SDX_UTILS_JS_TYPE_JS_OBJECT,
	SDX_UTILS_JS_TYPE_JS_ARRAY
} sdxutilsJsType;

struct _sdxutilsJsVariant {
	gint _retainCount;
	gboolean boolean;
	gdouble number;
	gchar* string;
	GHashTable* object;
	GList* array;
	sdxutilsJsType type;
};

struct _sdxgraphicsTextureRegion {
	gint _retainCount;
	sdxgraphicsSurfaceTextureSurface* texture;
	gint top;
	gint left;
	gint width;
	gint height;
	gint regionWidth;
	gint regionHeight;
	gdouble u;
	gdouble v;
	gdouble u2;
	gdouble v2;
};



void sdx_graphics_bitmap_font_free (sdxgraphicsBitmapFont* self);
void sdx_utils_json_free (sdxutilsJson* self);
void sdx_graphics_texture_region_free (sdxgraphicsTextureRegion* self);
void sdx_graphics_bitmap_font_data_free (sdxgraphicsBitmapFontData* self);
static void sdx_graphics_bitmap_font_instance_init (sdxgraphicsBitmapFont * self);
static void _sdx_graphics_texture_region_release0_ (gpointer var);
static void _g_list_free__sdx_graphics_texture_region_release0_ (GList* self);
#define SDX_GRAPHICS_BITMAP_FONT_LOG2_PAGE_SIZE 9
#define SDX_GRAPHICS_BITMAP_FONT_PAGE_SIZE (1 << SDX_GRAPHICS_BITMAP_FONT_LOG2_PAGE_SIZE)
#define SDX_GRAPHICS_BITMAP_FONT_PAGES (0x10000 / SDX_GRAPHICS_BITMAP_FONT_PAGE_SIZE)
sdxgraphicsBitmapFont* sdx_graphics_bitmap_font_retain (sdxgraphicsBitmapFont* self);
void sdx_graphics_bitmap_font_release (sdxgraphicsBitmapFont* self);
void sdx_graphics_bitmap_font_free (sdxgraphicsBitmapFont* self);
sdxgraphicsBitmapFont* sdx_graphics_bitmap_font_new (void);
void sdx_graphics_glyph_free (sdxgraphicsGlyph* self);
static void sdx_graphics_glyph_instance_init (sdxgraphicsGlyph * self);
sdxgraphicsGlyph* sdx_graphics_glyph_retain (sdxgraphicsGlyph* self);
void sdx_graphics_glyph_release (sdxgraphicsGlyph* self);
void sdx_graphics_glyph_free (sdxgraphicsGlyph* self);
gint sdx_graphics_glyph_getKerning (sdxgraphicsGlyph* self, gchar ch);
void sdx_graphics_glyph_setKerning (sdxgraphicsGlyph* self, gint ch, gint value);
sdxgraphicsGlyph* sdx_graphics_glyph_new (void);
void sdx_files_file_handle_free (sdxfilesFileHandle* self);
static void sdx_graphics_bitmap_font_data_instance_init (sdxgraphicsBitmapFontData * self);
sdxgraphicsBitmapFontData* sdx_graphics_bitmap_font_data_retain (sdxgraphicsBitmapFontData* self);
void sdx_graphics_bitmap_font_data_release (sdxgraphicsBitmapFontData* self);
void sdx_graphics_bitmap_font_data_free (sdxgraphicsBitmapFontData* self);
sdxgraphicsBitmapFontData* sdx_graphics_bitmap_font_data_new (sdxfilesFileHandle* fontFile, gboolean flip);
void sdx_graphics_bitmap_font_data_load (sdxgraphicsBitmapFontData* self, sdxfilesFileHandle* fontFile, gboolean flip);
GQuark sdx_sdl_exception_quark (void);
void sdx_utils_js_variant_free (sdxutilsJsVariant* self);
sdxutilsJsVariant* sdx_utils_json_parse (const gchar* source);
gchar* sdx_files_file_handle_read (sdxfilesFileHandle* self);
sdxutilsJsVariant* sdx_utils_js_variant_member (sdxutilsJsVariant* self, const gchar* key);
GType sdx_utils_js_type_get_type (void) G_GNUC_CONST;
sdxfilesFileHandle* sdx_files_file_handle_getParent (sdxfilesFileHandle* self);
sdxfilesFileHandle* sdx_files_file_handle_child (sdxfilesFileHandle* self, const gchar* name);
gchar* sdx_files_file_handle_getPath (sdxfilesFileHandle* self);
sdxgraphicsGlyph* sdx_graphics_bitmap_font_data_getGlyph (sdxgraphicsBitmapFontData* self, gchar ch);
sdxgraphicsGlyph* sdx_graphics_bitmap_font_data_getFirstGlyph (sdxgraphicsBitmapFontData* self);
void sdx_graphics_bitmap_font_data_setGlyph (sdxgraphicsBitmapFontData* self, gint ch, sdxgraphicsGlyph* glyph);
void sdx_graphics_bitmap_font_data_setGlyphRegion (sdxgraphicsBitmapFontData* self, sdxgraphicsGlyph* glyph, sdxgraphicsTextureRegion* region);
void sdx_graphics_surface_free (sdxgraphicsSurface* self);
gint sdx_graphics_surface_get_width (sdxgraphicsSurface* self);
gint sdx_graphics_surface_get_height (sdxgraphicsSurface* self);
gint sdx_graphics_texture_region_getRegionWidth (sdxgraphicsTextureRegion* self);
gint sdx_graphics_texture_region_getRegionHeight (sdxgraphicsTextureRegion* self);
void sdx_graphics_bitmap_font_data_setLineHeight (sdxgraphicsBitmapFontData* self, gdouble height);
gboolean sdx_graphics_bitmap_font_data_hasGlyph (sdxgraphicsBitmapFontData* self, gchar ch);
gint sdx_graphics_bitmap_font_data_getWrapIndex (sdxgraphicsBitmapFontData* self, gint start, GList* glyphs);
gboolean sdx_graphics_bitmap_font_data_isBreakChar (sdxgraphicsBitmapFontData* self, gchar c);
gchar* sdx_graphics_bitmap_font_data_getImagePath (sdxgraphicsBitmapFontData* self, gint index);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


static void _sdx_graphics_texture_region_release0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (sdx_graphics_texture_region_release (var), NULL));
}


static void _g_list_free__sdx_graphics_texture_region_release0_ (GList* self) {
	g_list_foreach (self, (GFunc) _sdx_graphics_texture_region_release0_, NULL);
	g_list_free (self);
}


sdxgraphicsBitmapFont* sdx_graphics_bitmap_font_retain (sdxgraphicsBitmapFont* self) {
	sdxgraphicsBitmapFont* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_atomic_int_add ((volatile gint *) (&self->_retainCount), 1);
	result = self;
	return result;
}


void sdx_graphics_bitmap_font_release (sdxgraphicsBitmapFont* self) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_atomic_int_dec_and_test ((volatile gint *) (&self->_retainCount));
	if (_tmp0_) {
		sdx_graphics_bitmap_font_free (self);
	}
}


sdxgraphicsBitmapFont* sdx_graphics_bitmap_font_new (void) {
	sdxgraphicsBitmapFont* self;
	self = g_slice_new0 (sdxgraphicsBitmapFont);
	sdx_graphics_bitmap_font_instance_init (self);
	return self;
}


static void sdx_graphics_bitmap_font_instance_init (sdxgraphicsBitmapFont * self) {
	self->_retainCount = 1;
}


void sdx_graphics_bitmap_font_free (sdxgraphicsBitmapFont* self) {
	_sdx_utils_json_release0 (self->dummy2);
	_sdx_graphics_texture_region_release0 (self->dummy);
	_sdx_graphics_bitmap_font_data_release0 (self->data);
	__g_list_free__sdx_graphics_texture_region_release0_0 (self->regions);
	g_slice_free (sdxgraphicsBitmapFont, self);
}


sdxgraphicsGlyph* sdx_graphics_glyph_retain (sdxgraphicsGlyph* self) {
	sdxgraphicsGlyph* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_atomic_int_add ((volatile gint *) (&self->_retainCount), 1);
	result = self;
	return result;
}


void sdx_graphics_glyph_release (sdxgraphicsGlyph* self) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_atomic_int_dec_and_test ((volatile gint *) (&self->_retainCount));
	if (_tmp0_) {
		sdx_graphics_glyph_free (self);
	}
}


gint sdx_graphics_glyph_getKerning (sdxgraphicsGlyph* self, gchar ch) {
	gint result = 0;
	gchar* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint _tmp0__length2 = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->kerning;
	_tmp0__length1 = self->kerning_length1;
	_tmp0__length2 = self->kerning_length2;
	if (_tmp0_ != NULL) {
		gint i = 0;
		gchar _tmp1_ = '\0';
		gchar j = '\0';
		gchar _tmp2_ = '\0';
		gchar* _tmp3_ = NULL;
		gint _tmp3__length1 = 0;
		gint _tmp3__length2 = 0;
		gint _tmp4_ = 0;
		gchar _tmp5_ = '\0';
		gchar _tmp6_ = '\0';
		_tmp1_ = ch;
		i = _tmp1_ >> SDX_GRAPHICS_BITMAP_FONT_LOG2_PAGE_SIZE;
		_tmp2_ = ch;
		j = _tmp2_ & (SDX_GRAPHICS_BITMAP_FONT_PAGE_SIZE - 1);
		_tmp3_ = self->kerning;
		_tmp3__length1 = self->kerning_length1;
		_tmp3__length2 = self->kerning_length2;
		_tmp4_ = i;
		_tmp5_ = j;
		_tmp6_ = _tmp3_[(_tmp4_ * _tmp3__length2) + _tmp5_];
		result = (gint) _tmp6_;
		return result;
	}
	result = 0;
	return result;
}


void sdx_graphics_glyph_setKerning (sdxgraphicsGlyph* self, gint ch, gint value) {
	gchar* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint _tmp0__length2 = 0;
	gint i = 0;
	gint _tmp2_ = 0;
	gint j = 0;
	gint _tmp3_ = 0;
	gchar* _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	gint _tmp4__length2 = 0;
	gint _tmp5_ = 0;
	gchar _tmp6_ = '\0';
	g_return_if_fail (self != NULL);
	_tmp0_ = self->kerning;
	_tmp0__length1 = self->kerning_length1;
	_tmp0__length2 = self->kerning_length2;
	if (_tmp0_ == NULL) {
		gchar* _tmp1_ = NULL;
		_tmp1_ = g_new0 (gchar, SDX_GRAPHICS_BITMAP_FONT_PAGES * SDX_GRAPHICS_BITMAP_FONT_PAGE_SIZE);
		self->kerning = (g_free (self->kerning), NULL);
		self->kerning = _tmp1_;
		self->kerning_length1 = SDX_GRAPHICS_BITMAP_FONT_PAGES;
		self->kerning_length2 = SDX_GRAPHICS_BITMAP_FONT_PAGE_SIZE;
	}
	_tmp2_ = ch;
	i = _tmp2_ >> SDX_GRAPHICS_BITMAP_FONT_LOG2_PAGE_SIZE;
	_tmp3_ = ch;
	j = _tmp3_ & (SDX_GRAPHICS_BITMAP_FONT_PAGE_SIZE - 1);
	_tmp4_ = self->kerning;
	_tmp4__length1 = self->kerning_length1;
	_tmp4__length2 = self->kerning_length2;
	_tmp5_ = value;
	_tmp4_[(i * _tmp4__length2) + j] = (gchar) _tmp5_;
	_tmp6_ = _tmp4_[(i * _tmp4__length2) + j];
}


sdxgraphicsGlyph* sdx_graphics_glyph_new (void) {
	sdxgraphicsGlyph* self;
	self = g_slice_new0 (sdxgraphicsGlyph);
	sdx_graphics_glyph_instance_init (self);
	return self;
}


static void sdx_graphics_glyph_instance_init (sdxgraphicsGlyph * self) {
	self->_retainCount = 1;
	self->page = 0;
}


void sdx_graphics_glyph_free (sdxgraphicsGlyph* self) {
	self->kerning = (g_free (self->kerning), NULL);
	g_slice_free (sdxgraphicsGlyph, self);
}


sdxgraphicsBitmapFontData* sdx_graphics_bitmap_font_data_retain (sdxgraphicsBitmapFontData* self) {
	sdxgraphicsBitmapFontData* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_atomic_int_add ((volatile gint *) (&self->_retainCount), 1);
	result = self;
	return result;
}


void sdx_graphics_bitmap_font_data_release (sdxgraphicsBitmapFontData* self) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_atomic_int_dec_and_test ((volatile gint *) (&self->_retainCount));
	if (_tmp0_) {
		sdx_graphics_bitmap_font_data_free (self);
	}
}


static gpointer _sdx_files_file_handle_retain0 (gpointer self) {
	return self ? sdx_files_file_handle_retain (self) : NULL;
}


sdxgraphicsBitmapFontData* sdx_graphics_bitmap_font_data_new (sdxfilesFileHandle* fontFile, gboolean flip) {
	sdxgraphicsBitmapFontData* self;
	sdxfilesFileHandle* _tmp0_ = NULL;
	self = g_slice_new0 (sdxgraphicsBitmapFontData);
	sdx_graphics_bitmap_font_data_instance_init (self);
	_tmp0_ = fontFile;
	if (_tmp0_ != NULL) {
		sdxfilesFileHandle* _tmp1_ = NULL;
		sdxfilesFileHandle* _tmp2_ = NULL;
		gboolean _tmp3_ = FALSE;
		sdxfilesFileHandle* _tmp4_ = NULL;
		gboolean _tmp5_ = FALSE;
		_tmp1_ = fontFile;
		_tmp2_ = _sdx_files_file_handle_retain0 (_tmp1_);
		_sdx_files_file_handle_release0 (self->fontFile);
		self->fontFile = _tmp2_;
		_tmp3_ = flip;
		self->flipped = _tmp3_;
		_tmp4_ = fontFile;
		_tmp5_ = flip;
		sdx_graphics_bitmap_font_data_load (self, _tmp4_, _tmp5_);
	}
	return self;
}


static gpointer _sdx_utils_js_variant_retain0 (gpointer self) {
	return self ? sdx_utils_js_variant_retain (self) : NULL;
}


static gpointer _sdx_graphics_glyph_retain0 (gpointer self) {
	return self ? sdx_graphics_glyph_retain (self) : NULL;
}


void sdx_graphics_bitmap_font_data_load (sdxgraphicsBitmapFontData* self, sdxfilesFileHandle* fontFile, gboolean flip) {
	gchar** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	sdxutilsJsVariant* json = NULL;
	sdxfilesFileHandle* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	sdxutilsJsVariant* _tmp5_ = NULL;
	sdxutilsJsVariant* _tmp6_ = NULL;
	gchar** padding = NULL;
	sdxutilsJsVariant* _tmp7_ = NULL;
	sdxutilsJsVariant* _tmp8_ = NULL;
	sdxutilsJsVariant* _tmp9_ = NULL;
	sdxutilsJsVariant* _tmp10_ = NULL;
	sdxutilsJsVariant* _tmp11_ = NULL;
	sdxutilsJsVariant* _tmp12_ = NULL;
	sdxutilsJsVariant* _tmp13_ = NULL;
	const gchar* _tmp14_ = NULL;
	gchar** _tmp15_ = NULL;
	gchar** _tmp16_ = NULL;
	gchar** _tmp17_ = NULL;
	gint _tmp17__length1 = 0;
	gint padding_length1 = 0;
	gint _padding_size_ = 0;
	gchar** _tmp18_ = NULL;
	gint _tmp18__length1 = 0;
	gchar** _tmp20_ = NULL;
	gint _tmp20__length1 = 0;
	const gchar* _tmp21_ = NULL;
	gint _tmp22_ = 0;
	gchar** _tmp23_ = NULL;
	gint _tmp23__length1 = 0;
	const gchar* _tmp24_ = NULL;
	gint _tmp25_ = 0;
	gchar** _tmp26_ = NULL;
	gint _tmp26__length1 = 0;
	const gchar* _tmp27_ = NULL;
	gint _tmp28_ = 0;
	gchar** _tmp29_ = NULL;
	gint _tmp29__length1 = 0;
	const gchar* _tmp30_ = NULL;
	gint _tmp31_ = 0;
	gdouble padY = 0.0;
	gdouble _tmp32_ = 0.0;
	gdouble _tmp33_ = 0.0;
	sdxutilsJsVariant* _tmp34_ = NULL;
	sdxutilsJsVariant* _tmp35_ = NULL;
	sdxutilsJsVariant* _tmp36_ = NULL;
	sdxutilsJsVariant* _tmp37_ = NULL;
	sdxutilsJsVariant* _tmp38_ = NULL;
	sdxutilsJsVariant* _tmp39_ = NULL;
	sdxutilsJsVariant* _tmp40_ = NULL;
	gdouble _tmp41_ = 0.0;
	gint baseLine = 0;
	sdxutilsJsVariant* _tmp42_ = NULL;
	sdxutilsJsVariant* _tmp43_ = NULL;
	sdxutilsJsVariant* _tmp44_ = NULL;
	sdxutilsJsVariant* _tmp45_ = NULL;
	sdxutilsJsVariant* _tmp46_ = NULL;
	sdxutilsJsVariant* _tmp47_ = NULL;
	sdxutilsJsVariant* _tmp48_ = NULL;
	gdouble _tmp49_ = 0.0;
	gint _tmp50_ = 0;
	const gchar** pages = NULL;
	sdxutilsJsVariant* _tmp51_ = NULL;
	sdxutilsJsVariant* _tmp52_ = NULL;
	sdxutilsJsVariant* _tmp53_ = NULL;
	sdxutilsJsVariant* _tmp54_ = NULL;
	sdxutilsJsVariant* _tmp55_ = NULL;
	GHashTable* _tmp56_ = NULL;
	gint _tmp57_ = 0;
	gconstpointer* _tmp58_ = NULL;
	const gchar** _tmp59_ = NULL;
	gint _tmp59__length1 = 0;
	gint pages_length1 = 0;
	gint _pages_size_ = 0;
	gint pageCount = 0;
	const gchar** _tmp60_ = NULL;
	gint _tmp60__length1 = 0;
	gint _tmp61_ = 0;
	gchar** _tmp62_ = NULL;
	sdxutilsJsVariant* _tmp93_ = NULL;
	sdxutilsJsVariant* _tmp94_ = NULL;
	sdxutilsJsVariant* _tmp95_ = NULL;
	sdxutilsJsVariant* _tmp96_ = NULL;
	sdxutilsJsVariant* _tmp97_ = NULL;
	sdxutilsJsVariant* _tmp98_ = NULL;
	sdxutilsJsVariant* _tmp99_ = NULL;
	GList* _tmp100_ = NULL;
	GList* _tmp101_ = NULL;
	gdouble _tmp171_ = 0.0;
	gdouble _tmp172_ = 0.0;
	sdxgraphicsGlyph* spaceGlyph = NULL;
	sdxgraphicsGlyph* _tmp173_ = NULL;
	sdxgraphicsGlyph* _tmp174_ = NULL;
	sdxgraphicsGlyph* _tmp184_ = NULL;
	gint _tmp185_ = 0;
	sdxgraphicsGlyph* _tmp193_ = NULL;
	gint _tmp194_ = 0;
	sdxgraphicsGlyph* xGlyph = NULL;
	gchar* _tmp195_ = NULL;
	gint _tmp195__length1 = 0;
	sdxgraphicsGlyph* _tmp199_ = NULL;
	sdxgraphicsGlyph* _tmp201_ = NULL;
	gint _tmp202_ = 0;
	gdouble _tmp203_ = 0.0;
	sdxgraphicsGlyph* capGlyph = NULL;
	gchar* _tmp204_ = NULL;
	gint _tmp204__length1 = 0;
	sdxgraphicsGlyph* _tmp208_ = NULL;
	gdouble _tmp233_ = 0.0;
	gdouble _tmp234_ = 0.0;
	gint _tmp235_ = 0;
	gdouble _tmp236_ = 0.0;
	gdouble _tmp237_ = 0.0;
	gboolean _tmp238_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (fontFile != NULL);
	_tmp0_ = self->imagePaths;
	_tmp0__length1 = self->imagePaths_length1;
	if (_tmp0_ != NULL) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (SDX_SDL_EXCEPTION, SDX_SDL_EXCEPTION_IllegalStateException, "Already loaded.");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp2_ = fontFile;
	_tmp3_ = sdx_files_file_handle_read (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = sdx_utils_json_parse (_tmp4_);
	_tmp6_ = _tmp5_;
	_g_free0 (_tmp4_);
	json = _tmp6_;
	_tmp7_ = json;
	_tmp8_ = sdx_utils_js_variant_member (_tmp7_, "font");
	_tmp9_ = _tmp8_;
	_tmp10_ = sdx_utils_js_variant_member (_tmp9_, "info");
	_tmp11_ = _tmp10_;
	_tmp12_ = sdx_utils_js_variant_member (_tmp11_, "padding");
	_tmp13_ = _tmp12_;
	_tmp14_ = _tmp13_->string;
	_tmp16_ = _tmp15_ = g_strsplit (_tmp14_, ",", 4);
	_tmp17_ = _tmp16_;
	_tmp17__length1 = _vala_array_length (_tmp15_);
	_sdx_utils_js_variant_release0 (_tmp13_);
	_sdx_utils_js_variant_release0 (_tmp11_);
	_sdx_utils_js_variant_release0 (_tmp9_);
	padding = _tmp17_;
	padding_length1 = _tmp17__length1;
	_padding_size_ = padding_length1;
	_tmp18_ = padding;
	_tmp18__length1 = padding_length1;
	if (_tmp18__length1 != 4) {
		GError* _tmp19_ = NULL;
		_tmp19_ = g_error_new_literal (SDX_SDL_EXCEPTION, SDX_SDL_EXCEPTION_RuntimeException, "Invalid padding.");
		_inner_error_ = _tmp19_;
		padding = (_vala_array_free (padding, padding_length1, (GDestroyNotify) g_free), NULL);
		_sdx_utils_js_variant_release0 (json);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp20_ = padding;
	_tmp20__length1 = padding_length1;
	_tmp21_ = _tmp20_[0];
	_tmp22_ = atoi (_tmp21_);
	self->padTop = (gdouble) _tmp22_;
	_tmp23_ = padding;
	_tmp23__length1 = padding_length1;
	_tmp24_ = _tmp23_[1];
	_tmp25_ = atoi (_tmp24_);
	self->padRight = (gdouble) _tmp25_;
	_tmp26_ = padding;
	_tmp26__length1 = padding_length1;
	_tmp27_ = _tmp26_[2];
	_tmp28_ = atoi (_tmp27_);
	self->padBottom = (gdouble) _tmp28_;
	_tmp29_ = padding;
	_tmp29__length1 = padding_length1;
	_tmp30_ = _tmp29_[3];
	_tmp31_ = atoi (_tmp30_);
	self->padLeft = (gdouble) _tmp31_;
	_tmp32_ = self->padTop;
	_tmp33_ = self->padBottom;
	padY = _tmp32_ + _tmp33_;
	_tmp34_ = json;
	_tmp35_ = sdx_utils_js_variant_member (_tmp34_, "font");
	_tmp36_ = _tmp35_;
	_tmp37_ = sdx_utils_js_variant_member (_tmp36_, "common");
	_tmp38_ = _tmp37_;
	_tmp39_ = sdx_utils_js_variant_member (_tmp38_, "lineHeight");
	_tmp40_ = _tmp39_;
	_tmp41_ = _tmp40_->number;
	self->lineHeight = (gdouble) ((gint) _tmp41_);
	_sdx_utils_js_variant_release0 (_tmp40_);
	_sdx_utils_js_variant_release0 (_tmp38_);
	_sdx_utils_js_variant_release0 (_tmp36_);
	_tmp42_ = json;
	_tmp43_ = sdx_utils_js_variant_member (_tmp42_, "font");
	_tmp44_ = _tmp43_;
	_tmp45_ = sdx_utils_js_variant_member (_tmp44_, "common");
	_tmp46_ = _tmp45_;
	_tmp47_ = sdx_utils_js_variant_member (_tmp46_, "base");
	_tmp48_ = _tmp47_;
	_tmp49_ = _tmp48_->number;
	_tmp50_ = (gint) _tmp49_;
	_sdx_utils_js_variant_release0 (_tmp48_);
	_sdx_utils_js_variant_release0 (_tmp46_);
	_sdx_utils_js_variant_release0 (_tmp44_);
	baseLine = _tmp50_;
	_tmp51_ = json;
	_tmp52_ = sdx_utils_js_variant_member (_tmp51_, "font");
	_tmp53_ = _tmp52_;
	_tmp54_ = sdx_utils_js_variant_member (_tmp53_, "pages");
	_tmp55_ = _tmp54_;
	_tmp56_ = _tmp55_->object;
	_tmp58_ = g_hash_table_get_keys_as_array (_tmp56_, &_tmp57_);
	_tmp59_ = _tmp58_;
	_tmp59__length1 = _tmp57_;
	_sdx_utils_js_variant_release0 (_tmp55_);
	_sdx_utils_js_variant_release0 (_tmp53_);
	pages = _tmp59_;
	pages_length1 = _tmp59__length1;
	_pages_size_ = pages_length1;
	_tmp60_ = pages;
	_tmp60__length1 = pages_length1;
	pageCount = _tmp60__length1;
	_tmp61_ = pageCount;
	_tmp62_ = g_new0 (gchar*, _tmp61_ + 1);
	self->imagePaths = (_vala_array_free (self->imagePaths, self->imagePaths_length1, (GDestroyNotify) g_free), NULL);
	self->imagePaths = _tmp62_;
	self->imagePaths_length1 = _tmp61_;
	{
		gint p = 0;
		p = 0;
		{
			gboolean _tmp63_ = FALSE;
			_tmp63_ = TRUE;
			while (TRUE) {
				gint _tmp65_ = 0;
				gint _tmp66_ = 0;
				sdxutilsJsVariant* node = NULL;
				sdxutilsJsVariant* _tmp67_ = NULL;
				sdxutilsJsVariant* _tmp68_ = NULL;
				sdxutilsJsVariant* _tmp69_ = NULL;
				sdxutilsJsVariant* _tmp70_ = NULL;
				sdxutilsJsVariant* _tmp71_ = NULL;
				const gchar** _tmp72_ = NULL;
				gint _tmp72__length1 = 0;
				gint _tmp73_ = 0;
				const gchar* _tmp74_ = NULL;
				sdxutilsJsVariant* _tmp75_ = NULL;
				sdxutilsJsVariant* _tmp76_ = NULL;
				gchar* filename = NULL;
				sdxutilsJsVariant* _tmp77_ = NULL;
				sdxutilsJsVariant* _tmp78_ = NULL;
				sdxutilsJsVariant* _tmp79_ = NULL;
				const gchar* _tmp80_ = NULL;
				gchar* _tmp81_ = NULL;
				gchar* _tmp82_ = NULL;
				gchar** _tmp83_ = NULL;
				gint _tmp83__length1 = 0;
				gint _tmp84_ = 0;
				sdxfilesFileHandle* _tmp85_ = NULL;
				sdxfilesFileHandle* _tmp86_ = NULL;
				sdxfilesFileHandle* _tmp87_ = NULL;
				const gchar* _tmp88_ = NULL;
				sdxfilesFileHandle* _tmp89_ = NULL;
				sdxfilesFileHandle* _tmp90_ = NULL;
				gchar* _tmp91_ = NULL;
				gchar* _tmp92_ = NULL;
				if (!_tmp63_) {
					gint _tmp64_ = 0;
					_tmp64_ = p;
					p = _tmp64_ + 1;
				}
				_tmp63_ = FALSE;
				_tmp65_ = p;
				_tmp66_ = pageCount;
				if (!(_tmp65_ < _tmp66_)) {
					break;
				}
				_tmp67_ = json;
				_tmp68_ = sdx_utils_js_variant_member (_tmp67_, "font");
				_tmp69_ = _tmp68_;
				_tmp70_ = sdx_utils_js_variant_member (_tmp69_, "pages");
				_tmp71_ = _tmp70_;
				_tmp72_ = pages;
				_tmp72__length1 = pages_length1;
				_tmp73_ = p;
				_tmp74_ = _tmp72_[_tmp73_];
				_tmp75_ = sdx_utils_js_variant_member (_tmp71_, _tmp74_);
				_tmp76_ = _tmp75_;
				_sdx_utils_js_variant_release0 (_tmp71_);
				_sdx_utils_js_variant_release0 (_tmp69_);
				node = _tmp76_;
				_tmp77_ = node;
				_tmp78_ = sdx_utils_js_variant_member (_tmp77_, "file");
				_tmp79_ = _tmp78_;
				_tmp80_ = _tmp79_->string;
				_tmp81_ = g_strdup (_tmp80_);
				_tmp82_ = _tmp81_;
				_sdx_utils_js_variant_release0 (_tmp79_);
				filename = _tmp82_;
				_tmp83_ = self->imagePaths;
				_tmp83__length1 = self->imagePaths_length1;
				_tmp84_ = p;
				_tmp85_ = fontFile;
				_tmp86_ = sdx_files_file_handle_getParent (_tmp85_);
				_tmp87_ = _tmp86_;
				_tmp88_ = filename;
				_tmp89_ = sdx_files_file_handle_child (_tmp87_, _tmp88_);
				_tmp90_ = _tmp89_;
				_tmp91_ = sdx_files_file_handle_getPath (_tmp90_);
				_g_free0 (_tmp83_[_tmp84_]);
				_tmp83_[_tmp84_] = _tmp91_;
				_tmp92_ = _tmp83_[_tmp84_];
				_sdx_files_file_handle_release0 (_tmp90_);
				_sdx_files_file_handle_release0 (_tmp87_);
				_g_free0 (filename);
				_sdx_utils_js_variant_release0 (node);
			}
		}
	}
	self->descent = (gdouble) 0;
	_tmp93_ = json;
	_tmp94_ = sdx_utils_js_variant_member (_tmp93_, "font");
	_tmp95_ = _tmp94_;
	_tmp96_ = sdx_utils_js_variant_member (_tmp95_, "chars");
	_tmp97_ = _tmp96_;
	_tmp98_ = sdx_utils_js_variant_member (_tmp97_, "char");
	_tmp99_ = _tmp98_;
	_tmp100_ = _tmp99_->array;
	_tmp101_ = _tmp100_;
	_sdx_utils_js_variant_release0 (_tmp99_);
	_sdx_utils_js_variant_release0 (_tmp97_);
	_sdx_utils_js_variant_release0 (_tmp95_);
	{
		GList* ch_collection = NULL;
		GList* ch_it = NULL;
		ch_collection = _tmp101_;
		for (ch_it = ch_collection; ch_it != NULL; ch_it = ch_it->next) {
			sdxutilsJsVariant* _tmp102_ = NULL;
			sdxutilsJsVariant* ch = NULL;
			_tmp102_ = _sdx_utils_js_variant_retain0 ((sdxutilsJsVariant*) ch_it->data);
			ch = _tmp102_;
			{
				sdxgraphicsGlyph* glyph = NULL;
				sdxgraphicsGlyph* _tmp103_ = NULL;
				sdxgraphicsGlyph* _tmp104_ = NULL;
				sdxutilsJsVariant* _tmp105_ = NULL;
				sdxutilsJsVariant* _tmp106_ = NULL;
				sdxutilsJsVariant* _tmp107_ = NULL;
				const gchar* _tmp108_ = NULL;
				gint _tmp109_ = 0;
				sdxgraphicsGlyph* _tmp110_ = NULL;
				sdxutilsJsVariant* _tmp111_ = NULL;
				sdxutilsJsVariant* _tmp112_ = NULL;
				sdxutilsJsVariant* _tmp113_ = NULL;
				const gchar* _tmp114_ = NULL;
				gint _tmp115_ = 0;
				sdxgraphicsGlyph* _tmp116_ = NULL;
				sdxutilsJsVariant* _tmp117_ = NULL;
				sdxutilsJsVariant* _tmp118_ = NULL;
				sdxutilsJsVariant* _tmp119_ = NULL;
				const gchar* _tmp120_ = NULL;
				gint _tmp121_ = 0;
				sdxgraphicsGlyph* _tmp122_ = NULL;
				sdxutilsJsVariant* _tmp123_ = NULL;
				sdxutilsJsVariant* _tmp124_ = NULL;
				sdxutilsJsVariant* _tmp125_ = NULL;
				const gchar* _tmp126_ = NULL;
				gint _tmp127_ = 0;
				sdxgraphicsGlyph* _tmp128_ = NULL;
				sdxutilsJsVariant* _tmp129_ = NULL;
				sdxutilsJsVariant* _tmp130_ = NULL;
				sdxutilsJsVariant* _tmp131_ = NULL;
				const gchar* _tmp132_ = NULL;
				gint _tmp133_ = 0;
				sdxgraphicsGlyph* _tmp134_ = NULL;
				sdxutilsJsVariant* _tmp135_ = NULL;
				sdxutilsJsVariant* _tmp136_ = NULL;
				sdxutilsJsVariant* _tmp137_ = NULL;
				const gchar* _tmp138_ = NULL;
				gint _tmp139_ = 0;
				gboolean _tmp140_ = FALSE;
				sdxgraphicsGlyph* _tmp155_ = NULL;
				sdxutilsJsVariant* _tmp156_ = NULL;
				sdxutilsJsVariant* _tmp157_ = NULL;
				sdxutilsJsVariant* _tmp158_ = NULL;
				const gchar* _tmp159_ = NULL;
				gint _tmp160_ = 0;
				gboolean _tmp161_ = FALSE;
				sdxgraphicsGlyph* _tmp162_ = NULL;
				gint _tmp163_ = 0;
				_tmp103_ = sdx_graphics_glyph_new ();
				glyph = _tmp103_;
				_tmp104_ = glyph;
				_tmp105_ = ch;
				_tmp106_ = sdx_utils_js_variant_member (_tmp105_, "id");
				_tmp107_ = _tmp106_;
				_tmp108_ = _tmp107_->string;
				_tmp109_ = atoi (_tmp108_);
				_tmp104_->id = _tmp109_;
				_sdx_utils_js_variant_release0 (_tmp107_);
				_tmp110_ = glyph;
				_tmp111_ = ch;
				_tmp112_ = sdx_utils_js_variant_member (_tmp111_, "x");
				_tmp113_ = _tmp112_;
				_tmp114_ = _tmp113_->string;
				_tmp115_ = atoi (_tmp114_);
				_tmp110_->x = _tmp115_;
				_sdx_utils_js_variant_release0 (_tmp113_);
				_tmp116_ = glyph;
				_tmp117_ = ch;
				_tmp118_ = sdx_utils_js_variant_member (_tmp117_, "y");
				_tmp119_ = _tmp118_;
				_tmp120_ = _tmp119_->string;
				_tmp121_ = atoi (_tmp120_);
				_tmp116_->y = _tmp121_;
				_sdx_utils_js_variant_release0 (_tmp119_);
				_tmp122_ = glyph;
				_tmp123_ = ch;
				_tmp124_ = sdx_utils_js_variant_member (_tmp123_, "width");
				_tmp125_ = _tmp124_;
				_tmp126_ = _tmp125_->string;
				_tmp127_ = atoi (_tmp126_);
				_tmp122_->width = _tmp127_;
				_sdx_utils_js_variant_release0 (_tmp125_);
				_tmp128_ = glyph;
				_tmp129_ = ch;
				_tmp130_ = sdx_utils_js_variant_member (_tmp129_, "height");
				_tmp131_ = _tmp130_;
				_tmp132_ = _tmp131_->string;
				_tmp133_ = atoi (_tmp132_);
				_tmp128_->height = _tmp133_;
				_sdx_utils_js_variant_release0 (_tmp131_);
				_tmp134_ = glyph;
				_tmp135_ = ch;
				_tmp136_ = sdx_utils_js_variant_member (_tmp135_, "xoffset");
				_tmp137_ = _tmp136_;
				_tmp138_ = _tmp137_->string;
				_tmp139_ = atoi (_tmp138_);
				_tmp134_->xoffset = _tmp139_;
				_sdx_utils_js_variant_release0 (_tmp137_);
				_tmp140_ = flip;
				if (_tmp140_) {
					sdxgraphicsGlyph* _tmp141_ = NULL;
					sdxutilsJsVariant* _tmp142_ = NULL;
					sdxutilsJsVariant* _tmp143_ = NULL;
					sdxutilsJsVariant* _tmp144_ = NULL;
					const gchar* _tmp145_ = NULL;
					gint _tmp146_ = 0;
					_tmp141_ = glyph;
					_tmp142_ = ch;
					_tmp143_ = sdx_utils_js_variant_member (_tmp142_, "yoffset");
					_tmp144_ = _tmp143_;
					_tmp145_ = _tmp144_->string;
					_tmp146_ = atoi (_tmp145_);
					_tmp141_->yoffset = _tmp146_;
					_sdx_utils_js_variant_release0 (_tmp144_);
				} else {
					sdxgraphicsGlyph* _tmp147_ = NULL;
					sdxgraphicsGlyph* _tmp148_ = NULL;
					gint _tmp149_ = 0;
					sdxutilsJsVariant* _tmp150_ = NULL;
					sdxutilsJsVariant* _tmp151_ = NULL;
					sdxutilsJsVariant* _tmp152_ = NULL;
					const gchar* _tmp153_ = NULL;
					gint _tmp154_ = 0;
					_tmp147_ = glyph;
					_tmp148_ = glyph;
					_tmp149_ = _tmp148_->height;
					_tmp150_ = ch;
					_tmp151_ = sdx_utils_js_variant_member (_tmp150_, "yoffset");
					_tmp152_ = _tmp151_;
					_tmp153_ = _tmp152_->string;
					_tmp154_ = atoi (_tmp153_);
					_tmp147_->yoffset = -(_tmp149_ + _tmp154_);
					_sdx_utils_js_variant_release0 (_tmp152_);
				}
				_tmp155_ = glyph;
				_tmp156_ = ch;
				_tmp157_ = sdx_utils_js_variant_member (_tmp156_, "xadvance");
				_tmp158_ = _tmp157_;
				_tmp159_ = _tmp158_->string;
				_tmp160_ = atoi (_tmp159_);
				_tmp155_->xadvance = _tmp160_;
				_sdx_utils_js_variant_release0 (_tmp158_);
				_tmp162_ = glyph;
				_tmp163_ = _tmp162_->width;
				if (_tmp163_ > 0) {
					sdxgraphicsGlyph* _tmp164_ = NULL;
					gint _tmp165_ = 0;
					_tmp164_ = glyph;
					_tmp165_ = _tmp164_->height;
					_tmp161_ = _tmp165_ > 0;
				} else {
					_tmp161_ = FALSE;
				}
				if (_tmp161_) {
					gint _tmp166_ = 0;
					sdxgraphicsGlyph* _tmp167_ = NULL;
					gint _tmp168_ = 0;
					gdouble _tmp169_ = 0.0;
					gdouble _tmp170_ = 0.0;
					_tmp166_ = baseLine;
					_tmp167_ = glyph;
					_tmp168_ = _tmp167_->yoffset;
					_tmp169_ = self->descent;
					_tmp170_ = fmin ((gdouble) (_tmp166_ + _tmp168_), _tmp169_);
					self->descent = _tmp170_;
				}
				_sdx_graphics_glyph_release0 (glyph);
				_sdx_utils_js_variant_release0 (ch);
			}
		}
	}
	_tmp171_ = self->descent;
	_tmp172_ = self->padBottom;
	self->descent = _tmp171_ + _tmp172_;
	_tmp173_ = sdx_graphics_bitmap_font_data_getGlyph (self, ' ');
	spaceGlyph = _tmp173_;
	_tmp174_ = spaceGlyph;
	if (_tmp174_ == NULL) {
		sdxgraphicsGlyph* _tmp175_ = NULL;
		sdxgraphicsGlyph* _tmp176_ = NULL;
		sdxgraphicsGlyph* xadvanceGlyph = NULL;
		sdxgraphicsGlyph* _tmp177_ = NULL;
		sdxgraphicsGlyph* _tmp178_ = NULL;
		sdxgraphicsGlyph* _tmp180_ = NULL;
		sdxgraphicsGlyph* _tmp181_ = NULL;
		gint _tmp182_ = 0;
		sdxgraphicsGlyph* _tmp183_ = NULL;
		_tmp175_ = sdx_graphics_glyph_new ();
		_sdx_graphics_glyph_release0 (spaceGlyph);
		spaceGlyph = _tmp175_;
		_tmp176_ = spaceGlyph;
		_tmp176_->id = (gint) ' ';
		_tmp177_ = sdx_graphics_bitmap_font_data_getGlyph (self, 'l');
		xadvanceGlyph = _tmp177_;
		_tmp178_ = xadvanceGlyph;
		if (_tmp178_ == NULL) {
			sdxgraphicsGlyph* _tmp179_ = NULL;
			_tmp179_ = sdx_graphics_bitmap_font_data_getFirstGlyph (self);
			_sdx_graphics_glyph_release0 (xadvanceGlyph);
			xadvanceGlyph = _tmp179_;
		}
		_tmp180_ = spaceGlyph;
		_tmp181_ = xadvanceGlyph;
		_tmp182_ = _tmp181_->xadvance;
		_tmp180_->xadvance = _tmp182_;
		_tmp183_ = spaceGlyph;
		sdx_graphics_bitmap_font_data_setGlyph (self, (gint) ' ', _tmp183_);
		_sdx_graphics_glyph_release0 (xadvanceGlyph);
	}
	_tmp184_ = spaceGlyph;
	_tmp185_ = _tmp184_->width;
	if (_tmp185_ == 0) {
		sdxgraphicsGlyph* _tmp186_ = NULL;
		gdouble _tmp187_ = 0.0;
		sdxgraphicsGlyph* _tmp188_ = NULL;
		gint _tmp189_ = 0;
		gdouble _tmp190_ = 0.0;
		sdxgraphicsGlyph* _tmp191_ = NULL;
		gdouble _tmp192_ = 0.0;
		_tmp186_ = spaceGlyph;
		_tmp187_ = self->padLeft;
		_tmp188_ = spaceGlyph;
		_tmp189_ = _tmp188_->xadvance;
		_tmp190_ = self->padRight;
		_tmp186_->width = (gint) ((_tmp187_ + _tmp189_) + _tmp190_);
		_tmp191_ = spaceGlyph;
		_tmp192_ = self->padLeft;
		_tmp191_->xoffset = (gint) (-_tmp192_);
	}
	_tmp193_ = spaceGlyph;
	_tmp194_ = _tmp193_->width;
	self->spaceWidth = (gdouble) _tmp194_;
	xGlyph = NULL;
	_tmp195_ = self->xChars;
	_tmp195__length1 = self->xChars_length1;
	{
		gchar* xChar_collection = NULL;
		gint xChar_collection_length1 = 0;
		gint _xChar_collection_size_ = 0;
		gint xChar_it = 0;
		xChar_collection = _tmp195_;
		xChar_collection_length1 = _tmp195__length1;
		for (xChar_it = 0; xChar_it < _tmp195__length1; xChar_it = xChar_it + 1) {
			gchar xChar = '\0';
			xChar = xChar_collection[xChar_it];
			{
				gchar _tmp196_ = '\0';
				sdxgraphicsGlyph* _tmp197_ = NULL;
				sdxgraphicsGlyph* _tmp198_ = NULL;
				_tmp196_ = xChar;
				_tmp197_ = sdx_graphics_bitmap_font_data_getGlyph (self, _tmp196_);
				_sdx_graphics_glyph_release0 (xGlyph);
				xGlyph = _tmp197_;
				_tmp198_ = xGlyph;
				if (_tmp198_ != NULL) {
					break;
				}
			}
		}
	}
	_tmp199_ = xGlyph;
	if (_tmp199_ == NULL) {
		sdxgraphicsGlyph* _tmp200_ = NULL;
		_tmp200_ = sdx_graphics_bitmap_font_data_getFirstGlyph (self);
		_sdx_graphics_glyph_release0 (xGlyph);
		xGlyph = _tmp200_;
	}
	_tmp201_ = xGlyph;
	_tmp202_ = _tmp201_->height;
	_tmp203_ = padY;
	self->xHeight = _tmp202_ - _tmp203_;
	capGlyph = NULL;
	_tmp204_ = self->capChars;
	_tmp204__length1 = self->capChars_length1;
	{
		gchar* capChar_collection = NULL;
		gint capChar_collection_length1 = 0;
		gint _capChar_collection_size_ = 0;
		gint capChar_it = 0;
		capChar_collection = _tmp204_;
		capChar_collection_length1 = _tmp204__length1;
		for (capChar_it = 0; capChar_it < _tmp204__length1; capChar_it = capChar_it + 1) {
			gchar capChar = '\0';
			capChar = capChar_collection[capChar_it];
			{
				gchar _tmp205_ = '\0';
				sdxgraphicsGlyph* _tmp206_ = NULL;
				sdxgraphicsGlyph* _tmp207_ = NULL;
				_tmp205_ = capChar;
				_tmp206_ = sdx_graphics_bitmap_font_data_getGlyph (self, _tmp205_);
				_sdx_graphics_glyph_release0 (capGlyph);
				capGlyph = _tmp206_;
				_tmp207_ = capGlyph;
				if (_tmp207_ != NULL) {
					break;
				}
			}
		}
	}
	_tmp208_ = capGlyph;
	if (_tmp208_ == NULL) {
		{
			gint p = 0;
			p = 0;
			{
				gboolean _tmp209_ = FALSE;
				_tmp209_ = TRUE;
				while (TRUE) {
					gint _tmp211_ = 0;
					if (!_tmp209_) {
						gint _tmp210_ = 0;
						_tmp210_ = p;
						p = _tmp210_ + 1;
					}
					_tmp209_ = FALSE;
					_tmp211_ = p;
					if (!(_tmp211_ < SDX_GRAPHICS_BITMAP_FONT_PAGES)) {
						break;
					}
					{
						gint g = 0;
						g = 0;
						{
							gboolean _tmp212_ = FALSE;
							_tmp212_ = TRUE;
							while (TRUE) {
								gint _tmp214_ = 0;
								sdxgraphicsGlyph* glyph = NULL;
								sdxgraphicsGlyph** _tmp215_ = NULL;
								gint _tmp215__length1 = 0;
								gint _tmp215__length2 = 0;
								gint _tmp216_ = 0;
								gint _tmp217_ = 0;
								sdxgraphicsGlyph* _tmp218_ = NULL;
								sdxgraphicsGlyph* _tmp219_ = NULL;
								gboolean _tmp220_ = FALSE;
								gboolean _tmp221_ = FALSE;
								sdxgraphicsGlyph* _tmp222_ = NULL;
								gdouble _tmp227_ = 0.0;
								sdxgraphicsGlyph* _tmp228_ = NULL;
								gint _tmp229_ = 0;
								gdouble _tmp230_ = 0.0;
								if (!_tmp212_) {
									gint _tmp213_ = 0;
									_tmp213_ = g;
									g = _tmp213_ + 1;
								}
								_tmp212_ = FALSE;
								_tmp214_ = g;
								if (!(_tmp214_ < SDX_GRAPHICS_BITMAP_FONT_PAGE_SIZE)) {
									break;
								}
								_tmp215_ = self->glyphs;
								_tmp215__length1 = self->glyphs_length1;
								_tmp215__length2 = self->glyphs_length2;
								_tmp216_ = p;
								_tmp217_ = g;
								_tmp218_ = _tmp215_[(_tmp216_ * _tmp215__length2) + _tmp217_];
								_tmp219_ = _sdx_graphics_glyph_retain0 (_tmp218_);
								glyph = _tmp219_;
								_tmp222_ = glyph;
								if (_tmp222_ == NULL) {
									_tmp221_ = TRUE;
								} else {
									sdxgraphicsGlyph* _tmp223_ = NULL;
									gint _tmp224_ = 0;
									_tmp223_ = glyph;
									_tmp224_ = _tmp223_->height;
									_tmp221_ = _tmp224_ == 0;
								}
								if (_tmp221_) {
									_tmp220_ = TRUE;
								} else {
									sdxgraphicsGlyph* _tmp225_ = NULL;
									gint _tmp226_ = 0;
									_tmp225_ = glyph;
									_tmp226_ = _tmp225_->width;
									_tmp220_ = _tmp226_ == 0;
								}
								if (_tmp220_) {
									_sdx_graphics_glyph_release0 (glyph);
									continue;
								}
								_tmp227_ = self->capHeight;
								_tmp228_ = glyph;
								_tmp229_ = _tmp228_->height;
								_tmp230_ = fmax (_tmp227_, (gdouble) _tmp229_);
								self->capHeight = _tmp230_;
								_sdx_graphics_glyph_release0 (glyph);
							}
						}
					}
				}
			}
		}
	} else {
		sdxgraphicsGlyph* _tmp231_ = NULL;
		gint _tmp232_ = 0;
		_tmp231_ = capGlyph;
		_tmp232_ = _tmp231_->height;
		self->capHeight = (gdouble) _tmp232_;
	}
	_tmp233_ = self->capHeight;
	_tmp234_ = padY;
	self->capHeight = _tmp233_ - _tmp234_;
	_tmp235_ = baseLine;
	_tmp236_ = self->capHeight;
	self->ascent = _tmp235_ - _tmp236_;
	_tmp237_ = self->lineHeight;
	self->down = -_tmp237_;
	_tmp238_ = flip;
	if (_tmp238_) {
		gdouble _tmp239_ = 0.0;
		gdouble _tmp240_ = 0.0;
		_tmp239_ = self->ascent;
		self->ascent = -_tmp239_;
		_tmp240_ = self->down;
		self->down = -_tmp240_;
	}
	_sdx_graphics_glyph_release0 (capGlyph);
	_sdx_graphics_glyph_release0 (xGlyph);
	_sdx_graphics_glyph_release0 (spaceGlyph);
	pages = (g_free (pages), NULL);
	padding = (_vala_array_free (padding, padding_length1, (GDestroyNotify) g_free), NULL);
	_sdx_utils_js_variant_release0 (json);
}


static gpointer _sdx_graphics_surface_retain0 (gpointer self) {
	return self ? sdx_graphics_surface_retain (self) : NULL;
}


void sdx_graphics_bitmap_font_data_setGlyphRegion (sdxgraphicsBitmapFontData* self, sdxgraphicsGlyph* glyph, sdxgraphicsTextureRegion* region) {
	sdxgraphicsSurfaceTextureSurface* texture = NULL;
	sdxgraphicsTextureRegion* _tmp0_ = NULL;
	sdxgraphicsSurfaceTextureSurface* _tmp1_ = NULL;
	sdxgraphicsSurfaceTextureSurface* _tmp2_ = NULL;
	gdouble invTexWidth = 0.0;
	sdxgraphicsSurfaceTextureSurface* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	gdouble invTexHeight = 0.0;
	sdxgraphicsSurfaceTextureSurface* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	gint offsetX = 0;
	gint offsetY = 0;
	gdouble u = 0.0;
	sdxgraphicsTextureRegion* _tmp9_ = NULL;
	gdouble _tmp10_ = 0.0;
	gdouble v = 0.0;
	sdxgraphicsTextureRegion* _tmp11_ = NULL;
	gdouble _tmp12_ = 0.0;
	gint regionWidth = 0;
	sdxgraphicsTextureRegion* _tmp13_ = NULL;
	gint _tmp14_ = 0;
	gint regionHeight = 0;
	sdxgraphicsTextureRegion* _tmp15_ = NULL;
	gint _tmp16_ = 0;
	gint x = 0;
	sdxgraphicsGlyph* _tmp17_ = NULL;
	gint _tmp18_ = 0;
	gint x2 = 0;
	sdxgraphicsGlyph* _tmp19_ = NULL;
	gint _tmp20_ = 0;
	sdxgraphicsGlyph* _tmp21_ = NULL;
	gint _tmp22_ = 0;
	gint y = 0;
	sdxgraphicsGlyph* _tmp23_ = NULL;
	gint _tmp24_ = 0;
	gint y2 = 0;
	sdxgraphicsGlyph* _tmp25_ = NULL;
	gint _tmp26_ = 0;
	sdxgraphicsGlyph* _tmp27_ = NULL;
	gint _tmp28_ = 0;
	gint _tmp29_ = 0;
	gint _tmp51_ = 0;
	sdxgraphicsGlyph* _tmp74_ = NULL;
	gdouble _tmp75_ = 0.0;
	gint _tmp76_ = 0;
	gdouble _tmp77_ = 0.0;
	sdxgraphicsGlyph* _tmp78_ = NULL;
	gdouble _tmp79_ = 0.0;
	gint _tmp80_ = 0;
	gdouble _tmp81_ = 0.0;
	gboolean _tmp82_ = FALSE;
	g_return_if_fail (self != NULL);
	g_return_if_fail (glyph != NULL);
	g_return_if_fail (region != NULL);
	_tmp0_ = region;
	_tmp1_ = _tmp0_->texture;
	_tmp2_ = _sdx_graphics_surface_retain0 (_tmp1_);
	texture = _tmp2_;
	_tmp3_ = texture;
	_tmp4_ = sdx_graphics_surface_get_width ((sdxgraphicsSurface*) _tmp3_);
	_tmp5_ = _tmp4_;
	invTexWidth = 1.0 / _tmp5_;
	_tmp6_ = texture;
	_tmp7_ = sdx_graphics_surface_get_height ((sdxgraphicsSurface*) _tmp6_);
	_tmp8_ = _tmp7_;
	invTexHeight = 1.0 / _tmp8_;
	offsetX = 0;
	offsetY = 0;
	_tmp9_ = region;
	_tmp10_ = _tmp9_->u;
	u = _tmp10_;
	_tmp11_ = region;
	_tmp12_ = _tmp11_->v;
	v = _tmp12_;
	_tmp13_ = region;
	_tmp14_ = sdx_graphics_texture_region_getRegionWidth (_tmp13_);
	regionWidth = _tmp14_;
	_tmp15_ = region;
	_tmp16_ = sdx_graphics_texture_region_getRegionHeight (_tmp15_);
	regionHeight = _tmp16_;
	_tmp17_ = glyph;
	_tmp18_ = _tmp17_->x;
	x = _tmp18_;
	_tmp19_ = glyph;
	_tmp20_ = _tmp19_->x;
	_tmp21_ = glyph;
	_tmp22_ = _tmp21_->width;
	x2 = _tmp20_ + _tmp22_;
	_tmp23_ = glyph;
	_tmp24_ = _tmp23_->y;
	y = _tmp24_;
	_tmp25_ = glyph;
	_tmp26_ = _tmp25_->y;
	_tmp27_ = glyph;
	_tmp28_ = _tmp27_->height;
	y2 = _tmp26_ + _tmp28_;
	_tmp29_ = offsetX;
	if (_tmp29_ > 0) {
		gint _tmp30_ = 0;
		gint _tmp31_ = 0;
		gint _tmp32_ = 0;
		gint _tmp41_ = 0;
		gint _tmp42_ = 0;
		gint _tmp43_ = 0;
		gint _tmp44_ = 0;
		_tmp30_ = x;
		_tmp31_ = offsetX;
		x = _tmp30_ - _tmp31_;
		_tmp32_ = x;
		if (_tmp32_ < 0) {
			sdxgraphicsGlyph* _tmp33_ = NULL;
			sdxgraphicsGlyph* _tmp34_ = NULL;
			gint _tmp35_ = 0;
			gint _tmp36_ = 0;
			sdxgraphicsGlyph* _tmp37_ = NULL;
			sdxgraphicsGlyph* _tmp38_ = NULL;
			gint _tmp39_ = 0;
			gint _tmp40_ = 0;
			_tmp33_ = glyph;
			_tmp34_ = glyph;
			_tmp35_ = _tmp34_->width;
			_tmp36_ = x;
			_tmp34_->width = _tmp35_ + _tmp36_;
			_tmp37_ = glyph;
			_tmp38_ = glyph;
			_tmp39_ = _tmp38_->xoffset;
			_tmp40_ = x;
			_tmp38_->xoffset = _tmp39_ - _tmp40_;
			x = 0;
		}
		_tmp41_ = x2;
		_tmp42_ = offsetX;
		x2 = _tmp41_ - _tmp42_;
		_tmp43_ = x2;
		_tmp44_ = regionWidth;
		if (_tmp43_ > _tmp44_) {
			sdxgraphicsGlyph* _tmp45_ = NULL;
			sdxgraphicsGlyph* _tmp46_ = NULL;
			gint _tmp47_ = 0;
			gint _tmp48_ = 0;
			gint _tmp49_ = 0;
			gint _tmp50_ = 0;
			_tmp45_ = glyph;
			_tmp46_ = glyph;
			_tmp47_ = _tmp46_->width;
			_tmp48_ = x2;
			_tmp49_ = regionWidth;
			_tmp46_->width = _tmp47_ - (_tmp48_ - _tmp49_);
			_tmp50_ = regionWidth;
			x2 = _tmp50_;
		}
	}
	_tmp51_ = offsetY;
	if (_tmp51_ > 0) {
		gint _tmp52_ = 0;
		gint _tmp53_ = 0;
		gint _tmp54_ = 0;
		gint _tmp59_ = 0;
		gint _tmp60_ = 0;
		gint _tmp61_ = 0;
		gint _tmp62_ = 0;
		_tmp52_ = y;
		_tmp53_ = offsetY;
		y = _tmp52_ - _tmp53_;
		_tmp54_ = y;
		if (_tmp54_ < 0) {
			sdxgraphicsGlyph* _tmp55_ = NULL;
			sdxgraphicsGlyph* _tmp56_ = NULL;
			gint _tmp57_ = 0;
			gint _tmp58_ = 0;
			_tmp55_ = glyph;
			_tmp56_ = glyph;
			_tmp57_ = _tmp56_->height;
			_tmp58_ = y;
			_tmp56_->height = _tmp57_ + _tmp58_;
			y = 0;
		}
		_tmp59_ = y2;
		_tmp60_ = offsetY;
		y2 = _tmp59_ - _tmp60_;
		_tmp61_ = y2;
		_tmp62_ = regionHeight;
		if (_tmp61_ > _tmp62_) {
			gint amount = 0;
			gint _tmp63_ = 0;
			gint _tmp64_ = 0;
			sdxgraphicsGlyph* _tmp65_ = NULL;
			sdxgraphicsGlyph* _tmp66_ = NULL;
			gint _tmp67_ = 0;
			gint _tmp68_ = 0;
			sdxgraphicsGlyph* _tmp69_ = NULL;
			sdxgraphicsGlyph* _tmp70_ = NULL;
			gint _tmp71_ = 0;
			gint _tmp72_ = 0;
			gint _tmp73_ = 0;
			_tmp63_ = y2;
			_tmp64_ = regionHeight;
			amount = _tmp63_ - _tmp64_;
			_tmp65_ = glyph;
			_tmp66_ = glyph;
			_tmp67_ = _tmp66_->height;
			_tmp68_ = amount;
			_tmp66_->height = _tmp67_ - _tmp68_;
			_tmp69_ = glyph;
			_tmp70_ = glyph;
			_tmp71_ = _tmp70_->yoffset;
			_tmp72_ = amount;
			_tmp70_->yoffset = _tmp71_ + _tmp72_;
			_tmp73_ = regionHeight;
			y2 = _tmp73_;
		}
	}
	_tmp74_ = glyph;
	_tmp75_ = u;
	_tmp76_ = x;
	_tmp77_ = invTexWidth;
	_tmp74_->u = _tmp75_ + (_tmp76_ * _tmp77_);
	_tmp78_ = glyph;
	_tmp79_ = u;
	_tmp80_ = x2;
	_tmp81_ = invTexWidth;
	_tmp78_->u2 = _tmp79_ + (_tmp80_ * _tmp81_);
	_tmp82_ = self->flipped;
	if (_tmp82_) {
		sdxgraphicsGlyph* _tmp83_ = NULL;
		gdouble _tmp84_ = 0.0;
		gint _tmp85_ = 0;
		gdouble _tmp86_ = 0.0;
		sdxgraphicsGlyph* _tmp87_ = NULL;
		gdouble _tmp88_ = 0.0;
		gint _tmp89_ = 0;
		gdouble _tmp90_ = 0.0;
		_tmp83_ = glyph;
		_tmp84_ = v;
		_tmp85_ = y;
		_tmp86_ = invTexHeight;
		_tmp83_->v = _tmp84_ + (_tmp85_ * _tmp86_);
		_tmp87_ = glyph;
		_tmp88_ = v;
		_tmp89_ = y2;
		_tmp90_ = invTexHeight;
		_tmp87_->v2 = _tmp88_ + (_tmp89_ * _tmp90_);
	} else {
		sdxgraphicsGlyph* _tmp91_ = NULL;
		gdouble _tmp92_ = 0.0;
		gint _tmp93_ = 0;
		gdouble _tmp94_ = 0.0;
		sdxgraphicsGlyph* _tmp95_ = NULL;
		gdouble _tmp96_ = 0.0;
		gint _tmp97_ = 0;
		gdouble _tmp98_ = 0.0;
		_tmp91_ = glyph;
		_tmp92_ = v;
		_tmp93_ = y;
		_tmp94_ = invTexHeight;
		_tmp91_->v2 = _tmp92_ + (_tmp93_ * _tmp94_);
		_tmp95_ = glyph;
		_tmp96_ = v;
		_tmp97_ = y2;
		_tmp98_ = invTexHeight;
		_tmp95_->v = _tmp96_ + (_tmp97_ * _tmp98_);
	}
	_sdx_graphics_surface_release0 (texture);
}


void sdx_graphics_bitmap_font_data_setLineHeight (sdxgraphicsBitmapFontData* self, gdouble height) {
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	gdouble _tmp2_ = 0.0;
	gboolean _tmp3_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = height;
	_tmp1_ = self->scaleY;
	self->lineHeight = _tmp0_ * _tmp1_;
	_tmp3_ = self->flipped;
	if (_tmp3_) {
		gdouble _tmp4_ = 0.0;
		_tmp4_ = self->lineHeight;
		_tmp2_ = _tmp4_;
	} else {
		gdouble _tmp5_ = 0.0;
		_tmp5_ = self->lineHeight;
		_tmp2_ = -_tmp5_;
	}
	self->down = _tmp2_;
}


void sdx_graphics_bitmap_font_data_setGlyph (sdxgraphicsBitmapFontData* self, gint ch, sdxgraphicsGlyph* glyph) {
	sdxgraphicsGlyph** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint _tmp0__length2 = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	sdxgraphicsGlyph* _tmp3_ = NULL;
	sdxgraphicsGlyph* _tmp4_ = NULL;
	sdxgraphicsGlyph* _tmp5_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (glyph != NULL);
	_tmp0_ = self->glyphs;
	_tmp0__length1 = self->glyphs_length1;
	_tmp0__length2 = self->glyphs_length2;
	_tmp1_ = ch;
	_tmp2_ = ch;
	_tmp3_ = glyph;
	_tmp4_ = _sdx_graphics_glyph_retain0 (_tmp3_);
	_sdx_graphics_glyph_release0 (_tmp0_[((_tmp1_ / SDX_GRAPHICS_BITMAP_FONT_PAGE_SIZE) * _tmp0__length2) + (_tmp2_ & (SDX_GRAPHICS_BITMAP_FONT_PAGE_SIZE - 1))]);
	_tmp0_[((_tmp1_ / SDX_GRAPHICS_BITMAP_FONT_PAGE_SIZE) * _tmp0__length2) + (_tmp2_ & (SDX_GRAPHICS_BITMAP_FONT_PAGE_SIZE - 1))] = _tmp4_;
	_tmp5_ = _tmp0_[((_tmp1_ / SDX_GRAPHICS_BITMAP_FONT_PAGE_SIZE) * _tmp0__length2) + (_tmp2_ & (SDX_GRAPHICS_BITMAP_FONT_PAGE_SIZE - 1))];
}


sdxgraphicsGlyph* sdx_graphics_bitmap_font_data_getFirstGlyph (sdxgraphicsBitmapFontData* self) {
	sdxgraphicsGlyph* result = NULL;
	GError* _tmp18_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	{
		gint p = 0;
		p = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				gint _tmp2_ = 0;
				if (!_tmp0_) {
					gint _tmp1_ = 0;
					_tmp1_ = p;
					p = _tmp1_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp2_ = p;
				if (!(_tmp2_ < SDX_GRAPHICS_BITMAP_FONT_PAGES)) {
					break;
				}
				{
					gint g = 0;
					g = 0;
					{
						gboolean _tmp3_ = FALSE;
						_tmp3_ = TRUE;
						while (TRUE) {
							gint _tmp5_ = 0;
							sdxgraphicsGlyph* glyph = NULL;
							sdxgraphicsGlyph** _tmp6_ = NULL;
							gint _tmp6__length1 = 0;
							gint _tmp6__length2 = 0;
							gint _tmp7_ = 0;
							gint _tmp8_ = 0;
							sdxgraphicsGlyph* _tmp9_ = NULL;
							sdxgraphicsGlyph* _tmp10_ = NULL;
							gboolean _tmp11_ = FALSE;
							gboolean _tmp12_ = FALSE;
							sdxgraphicsGlyph* _tmp13_ = NULL;
							if (!_tmp3_) {
								gint _tmp4_ = 0;
								_tmp4_ = g;
								g = _tmp4_ + 1;
							}
							_tmp3_ = FALSE;
							_tmp5_ = g;
							if (!(_tmp5_ < SDX_GRAPHICS_BITMAP_FONT_PAGE_SIZE)) {
								break;
							}
							_tmp6_ = self->glyphs;
							_tmp6__length1 = self->glyphs_length1;
							_tmp6__length2 = self->glyphs_length2;
							_tmp7_ = p;
							_tmp8_ = g;
							_tmp9_ = _tmp6_[(_tmp7_ * _tmp6__length2) + _tmp8_];
							_tmp10_ = _sdx_graphics_glyph_retain0 (_tmp9_);
							glyph = _tmp10_;
							_tmp13_ = glyph;
							if (_tmp13_ == NULL) {
								_tmp12_ = TRUE;
							} else {
								sdxgraphicsGlyph* _tmp14_ = NULL;
								gint _tmp15_ = 0;
								_tmp14_ = glyph;
								_tmp15_ = _tmp14_->height;
								_tmp12_ = _tmp15_ == 0;
							}
							if (_tmp12_) {
								_tmp11_ = TRUE;
							} else {
								sdxgraphicsGlyph* _tmp16_ = NULL;
								gint _tmp17_ = 0;
								_tmp16_ = glyph;
								_tmp17_ = _tmp16_->width;
								_tmp11_ = _tmp17_ == 0;
							}
							if (_tmp11_) {
								_sdx_graphics_glyph_release0 (glyph);
								continue;
							}
							result = glyph;
							return result;
						}
					}
				}
			}
		}
	}
	_tmp18_ = g_error_new_literal (SDX_SDL_EXCEPTION, SDX_SDL_EXCEPTION_RuntimeException, "No glyphs found.");
	_inner_error_ = _tmp18_;
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return NULL;
}


gboolean sdx_graphics_bitmap_font_data_hasGlyph (sdxgraphicsBitmapFontData* self, gchar ch) {
	gboolean result = FALSE;
	sdxgraphicsGlyph* _tmp0_ = NULL;
	gchar _tmp1_ = '\0';
	sdxgraphicsGlyph* _tmp2_ = NULL;
	sdxgraphicsGlyph* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->missingGlyph;
	if (_tmp0_ != NULL) {
		result = TRUE;
		return result;
	}
	_tmp1_ = ch;
	_tmp2_ = sdx_graphics_bitmap_font_data_getGlyph (self, _tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = _tmp3_ != NULL;
	_sdx_graphics_glyph_release0 (_tmp3_);
	result = _tmp4_;
	return result;
}


sdxgraphicsGlyph* sdx_graphics_bitmap_font_data_getGlyph (sdxgraphicsBitmapFontData* self, gchar ch) {
	sdxgraphicsGlyph* result = NULL;
	sdxgraphicsGlyph** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint _tmp0__length2 = 0;
	gchar _tmp1_ = '\0';
	gchar _tmp2_ = '\0';
	sdxgraphicsGlyph* _tmp3_ = NULL;
	sdxgraphicsGlyph* _tmp4_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->glyphs;
	_tmp0__length1 = self->glyphs_length1;
	_tmp0__length2 = self->glyphs_length2;
	_tmp1_ = ch;
	_tmp2_ = ch;
	_tmp3_ = _tmp0_[((_tmp1_ / SDX_GRAPHICS_BITMAP_FONT_PAGE_SIZE) * _tmp0__length2) + (_tmp2_ & (SDX_GRAPHICS_BITMAP_FONT_PAGE_SIZE - 1))];
	_tmp4_ = _sdx_graphics_glyph_retain0 (_tmp3_);
	result = _tmp4_;
	return result;
}


gint sdx_graphics_bitmap_font_data_getWrapIndex (sdxgraphicsBitmapFontData* self, gint start, GList* glyphs) {
	gint result = 0;
	g_return_val_if_fail (self != NULL, 0);
	result = 0;
	return result;
}


gboolean sdx_graphics_bitmap_font_data_isBreakChar (sdxgraphicsBitmapFontData* self, gchar c) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	result = FALSE;
	return result;
}


gchar* sdx_graphics_bitmap_font_data_getImagePath (sdxgraphicsBitmapFontData* self, gint index) {
	gchar* result = NULL;
	gchar** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint _tmp1_ = 0;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->imagePaths;
	_tmp0__length1 = self->imagePaths_length1;
	_tmp1_ = index;
	_tmp2_ = _tmp0_[_tmp1_];
	_tmp3_ = g_strdup (_tmp2_);
	result = _tmp3_;
	return result;
}


static void sdx_graphics_bitmap_font_data_instance_init (sdxgraphicsBitmapFontData * self) {
	sdxgraphicsGlyph** _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	self->_retainCount = 1;
	self->capHeight = (gdouble) 1;
	self->blankLineScale = (gdouble) 1;
	self->scaleX = (gdouble) 1;
	self->scaleY = (gdouble) 1;
	_tmp0_ = g_new0 (sdxgraphicsGlyph*, (SDX_GRAPHICS_BITMAP_FONT_PAGES * SDX_GRAPHICS_BITMAP_FONT_PAGE_SIZE) + 1);
	self->glyphs = _tmp0_;
	self->glyphs_length1 = SDX_GRAPHICS_BITMAP_FONT_PAGES;
	self->glyphs_length2 = SDX_GRAPHICS_BITMAP_FONT_PAGE_SIZE;
	self->xHeight = (gdouble) 1;
	_tmp1_ = g_new0 (gchar, 13);
	_tmp1_[0] = 'x';
	_tmp1_[1] = 'e';
	_tmp1_[2] = 'a';
	_tmp1_[3] = 'o';
	_tmp1_[4] = 'n';
	_tmp1_[5] = 's';
	_tmp1_[6] = 'r';
	_tmp1_[7] = 'c';
	_tmp1_[8] = 'u';
	_tmp1_[9] = 'm';
	_tmp1_[10] = 'v';
	_tmp1_[11] = 'w';
	_tmp1_[12] = 'z';
	self->xChars = _tmp1_;
	self->xChars_length1 = 13;
	_tmp2_ = g_new0 (gchar, 26);
	_tmp2_[0] = 'M';
	_tmp2_[1] = 'N';
	_tmp2_[2] = 'B';
	_tmp2_[3] = 'D';
	_tmp2_[4] = 'C';
	_tmp2_[5] = 'E';
	_tmp2_[6] = 'F';
	_tmp2_[7] = 'K';
	_tmp2_[8] = 'A';
	_tmp2_[9] = 'G';
	_tmp2_[10] = 'H';
	_tmp2_[11] = 'I';
	_tmp2_[12] = 'J';
	_tmp2_[13] = 'L';
	_tmp2_[14] = 'O';
	_tmp2_[15] = 'P';
	_tmp2_[16] = 'Q';
	_tmp2_[17] = 'R';
	_tmp2_[18] = 'S';
	_tmp2_[19] = 'T';
	_tmp2_[20] = 'U';
	_tmp2_[21] = 'V';
	_tmp2_[22] = 'W';
	_tmp2_[23] = 'X';
	_tmp2_[24] = 'Y';
	_tmp2_[25] = 'Z';
	self->capChars = _tmp2_;
	self->capChars_length1 = 26;
}


void sdx_graphics_bitmap_font_data_free (sdxgraphicsBitmapFontData* self) {
	self->imagePaths = (_vala_array_free (self->imagePaths, self->imagePaths_length1, (GDestroyNotify) g_free), NULL);
	_sdx_files_file_handle_release0 (self->fontFile);
	self->glyphs = (_vala_array_free (self->glyphs, self->glyphs_length1 * self->glyphs_length2, (GDestroyNotify) sdx_graphics_glyph_release), NULL);
	_sdx_graphics_glyph_release0 (self->missingGlyph);
	self->breakChars = (g_free (self->breakChars), NULL);
	self->xChars = (g_free (self->xChars), NULL);
	self->capChars = (g_free (self->capChars), NULL);
	g_slice_free (sdxgraphicsBitmapFontData, self);
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



