/* Camera.c generated by valac 0.34.8, the Vala compiler
 * generated from Camera.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>

typedef struct _sdxgraphicsCamera sdxgraphicsCamera;

#define SDX_GRAPHICS_CAMERA_TYPE_KIND (sdx_graphics_camera_kind_get_type ())

#define TYPE_VECTOR2D (vector2d_get_type ())
typedef struct _Vector2d Vector2d;

#define TYPE_POINT2D (point2d_get_type ())
typedef struct _Point2d Point2d;
typedef sdxgraphicsCamera sdxgraphicsCameraInnerCamera;
typedef sdxgraphicsCamera sdxgraphicsCameraFluidCamera;
typedef sdxgraphicsCamera sdxgraphicsCameraSimpleCamera;

typedef enum  {
	SDX_GRAPHICS_CAMERA_KIND_FluidCamera,
	SDX_GRAPHICS_CAMERA_KIND_InnerCamera,
	SDX_GRAPHICS_CAMERA_KIND_SimpleCamera
} sdxgraphicsCameraKind;

struct _Vector2d {
	gdouble x;
	gdouble y;
};

struct _sdxgraphicsCamera {
	gint _retainCount;
	sdxgraphicsCameraKind kind;
	Vector2d position;
};

struct _Point2d {
	gdouble x;
	gdouble y;
};


extern gint sdx_width;

void sdx_graphics_camera_free (sdxgraphicsCamera* self);
GType sdx_graphics_camera_kind_get_type (void) G_GNUC_CONST;
GType vector2d_get_type (void) G_GNUC_CONST;
Vector2d* vector2d_dup (const Vector2d* self);
void vector2d_free (Vector2d* self);
static void sdx_graphics_camera_instance_init (sdxgraphicsCamera * self);
sdxgraphicsCamera* sdx_graphics_camera_retain (sdxgraphicsCamera* self);
void sdx_graphics_camera_release (sdxgraphicsCamera* self);
void sdx_graphics_camera_free (sdxgraphicsCamera* self);
GType point2d_get_type (void) G_GNUC_CONST;
Point2d* point2d_dup (const Point2d* self);
void point2d_free (Point2d* self);
void sdx_graphics_camera_setPosition (sdxgraphicsCamera* self, Point2d* position);
sdxgraphicsCamera* sdx_graphics_camera_new (void);
sdxgraphicsCameraInnerCamera* sdx_graphics_camera_inner_camera_new (gdouble x, gdouble y);
void sdx_graphics_camera_inner_camera_setPosition (sdxgraphicsCameraInnerCamera* self, Point2d* player);
gdouble clamp (gdouble value, gdouble low, gdouble hi);
sdxgraphicsCameraFluidCamera* sdx_graphics_camera_fluid_camera_new (gdouble x, gdouble y);
void sdx_graphics_camera_fluid_camera_setPosition (sdxgraphicsCameraFluidCamera* self, Point2d* player);
sdxgraphicsCameraSimpleCamera* sdx_graphics_camera_simple_camera_new (gdouble x, gdouble y);
void sdx_graphics_camera_simple_camera_setPosition (sdxgraphicsCameraSimpleCamera* self, Point2d* player);


GType sdx_graphics_camera_kind_get_type (void) {
	static volatile gsize sdx_graphics_camera_kind_type_id__volatile = 0;
	if (g_once_init_enter (&sdx_graphics_camera_kind_type_id__volatile)) {
		static const GEnumValue values[] = {{SDX_GRAPHICS_CAMERA_KIND_FluidCamera, "SDX_GRAPHICS_CAMERA_KIND_FluidCamera", "fluidcamera"}, {SDX_GRAPHICS_CAMERA_KIND_InnerCamera, "SDX_GRAPHICS_CAMERA_KIND_InnerCamera", "innercamera"}, {SDX_GRAPHICS_CAMERA_KIND_SimpleCamera, "SDX_GRAPHICS_CAMERA_KIND_SimpleCamera", "simplecamera"}, {0, NULL, NULL}};
		GType sdx_graphics_camera_kind_type_id;
		sdx_graphics_camera_kind_type_id = g_enum_register_static ("sdxgraphicsCameraKind", values);
		g_once_init_leave (&sdx_graphics_camera_kind_type_id__volatile, sdx_graphics_camera_kind_type_id);
	}
	return sdx_graphics_camera_kind_type_id__volatile;
}


sdxgraphicsCamera* sdx_graphics_camera_retain (sdxgraphicsCamera* self) {
	sdxgraphicsCamera* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_atomic_int_add ((volatile gint *) (&self->_retainCount), 1);
	result = self;
	return result;
}


void sdx_graphics_camera_release (sdxgraphicsCamera* self) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_atomic_int_dec_and_test ((volatile gint *) (&self->_retainCount));
	if (_tmp0_) {
		sdx_graphics_camera_free (self);
	}
}


/**
         * setPosition
         * 
         * set the camera (x, y) location
         */
void sdx_graphics_camera_setPosition (sdxgraphicsCamera* self, Point2d* position) {
	Point2d _tmp0_ = {0};
	gdouble _tmp1_ = 0.0;
	Point2d _tmp2_ = {0};
	gdouble _tmp3_ = 0.0;
	Vector2d _tmp4_ = {0};
	g_return_if_fail (self != NULL);
	g_return_if_fail (position != NULL);
	_tmp0_ = *position;
	_tmp1_ = _tmp0_.x;
	_tmp2_ = *position;
	_tmp3_ = _tmp2_.y;
	_tmp4_.x = _tmp1_;
	_tmp4_.y = _tmp3_;
	self->position = _tmp4_;
}


sdxgraphicsCamera* sdx_graphics_camera_new (void) {
	sdxgraphicsCamera* self;
	self = g_slice_new0 (sdxgraphicsCamera);
	sdx_graphics_camera_instance_init (self);
	return self;
}


/**
             * InnerCamera
             * 
             */
sdxgraphicsCameraInnerCamera* sdx_graphics_camera_inner_camera_new (gdouble x, gdouble y) {
	sdxgraphicsCameraInnerCamera* self;
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	Vector2d _tmp2_ = {0};
	self = (sdxgraphicsCameraInnerCamera*) sdx_graphics_camera_new ();
	((sdxgraphicsCamera*) self)->kind = SDX_GRAPHICS_CAMERA_KIND_InnerCamera;
	_tmp0_ = x;
	_tmp1_ = y;
	_tmp2_.x = _tmp0_;
	_tmp2_.y = _tmp1_;
	((sdxgraphicsCamera*) self)->position = _tmp2_;
	return self;
}


void sdx_graphics_camera_inner_camera_setPosition (sdxgraphicsCameraInnerCamera* self, Point2d* player) {
	gdouble area = 0.0;
	Point2d _tmp0_ = {0};
	gdouble _tmp1_ = 0.0;
	gint _tmp2_ = 0;
	Vector2d _tmp3_ = {0};
	gdouble _tmp4_ = 0.0;
	gdouble _tmp5_ = 0.0;
	Vector2d _tmp6_ = {0};
	gdouble _tmp7_ = 0.0;
	Point2d _tmp8_ = {0};
	g_return_if_fail (self != NULL);
	g_return_if_fail (player != NULL);
	_tmp0_ = *player;
	_tmp1_ = _tmp0_.x;
	_tmp2_ = sdx_width;
	area = _tmp1_ - (((gdouble) _tmp2_) / 2);
	_tmp3_ = ((sdxgraphicsCamera*) self)->position;
	_tmp4_ = _tmp3_.x;
	_tmp5_ = clamp (_tmp4_, area - 100, area + 100);
	_tmp6_ = ((sdxgraphicsCamera*) self)->position;
	_tmp7_ = _tmp6_.y;
	_tmp8_.x = _tmp5_;
	_tmp8_.y = _tmp7_;
	sdx_graphics_camera_setPosition ((sdxgraphicsCamera*) self, &_tmp8_);
}


/**
             * FluidCamera
             * 
             */
sdxgraphicsCameraFluidCamera* sdx_graphics_camera_fluid_camera_new (gdouble x, gdouble y) {
	sdxgraphicsCameraFluidCamera* self;
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	Vector2d _tmp2_ = {0};
	self = (sdxgraphicsCameraFluidCamera*) sdx_graphics_camera_new ();
	((sdxgraphicsCamera*) self)->kind = SDX_GRAPHICS_CAMERA_KIND_FluidCamera;
	_tmp0_ = x;
	_tmp1_ = y;
	_tmp2_.x = _tmp0_;
	_tmp2_.y = _tmp1_;
	((sdxgraphicsCamera*) self)->position = _tmp2_;
	return self;
}


void sdx_graphics_camera_fluid_camera_setPosition (sdxgraphicsCameraFluidCamera* self, Point2d* player) {
	gdouble dist = 0.0;
	Vector2d _tmp0_ = {0};
	gdouble _tmp1_ = 0.0;
	Point2d _tmp2_ = {0};
	gdouble _tmp3_ = 0.0;
	gint _tmp4_ = 0;
	gdouble _tmp5_ = 0.0;
	gdouble _tmp6_ = 0.0;
	Vector2d _tmp7_ = {0};
	gdouble _tmp8_ = 0.0;
	Point2d _tmp9_ = {0};
	g_return_if_fail (self != NULL);
	g_return_if_fail (player != NULL);
	_tmp0_ = ((sdxgraphicsCamera*) self)->position;
	_tmp1_ = _tmp0_.x;
	_tmp2_ = *player;
	_tmp3_ = _tmp2_.x;
	_tmp4_ = sdx_width;
	dist = (_tmp1_ - _tmp3_) + (((gdouble) _tmp4_) / 2);
	_tmp5_ = ((sdxgraphicsCamera*) self)->position.x;
	((sdxgraphicsCamera*) self)->position.x = _tmp5_ + ((-0.05) * dist);
	_tmp6_ = ((sdxgraphicsCamera*) self)->position.x;
	_tmp7_ = ((sdxgraphicsCamera*) self)->position;
	_tmp8_ = _tmp7_.y;
	_tmp9_.x = _tmp6_;
	_tmp9_.y = _tmp8_;
	sdx_graphics_camera_setPosition ((sdxgraphicsCamera*) self, &_tmp9_);
}


/**
             * SimpleCamera
             * 
             */
sdxgraphicsCameraSimpleCamera* sdx_graphics_camera_simple_camera_new (gdouble x, gdouble y) {
	sdxgraphicsCameraSimpleCamera* self;
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	Vector2d _tmp2_ = {0};
	self = (sdxgraphicsCameraSimpleCamera*) sdx_graphics_camera_new ();
	((sdxgraphicsCamera*) self)->kind = SDX_GRAPHICS_CAMERA_KIND_SimpleCamera;
	_tmp0_ = x;
	_tmp1_ = y;
	_tmp2_.x = _tmp0_;
	_tmp2_.y = _tmp1_;
	((sdxgraphicsCamera*) self)->position = _tmp2_;
	return self;
}


void sdx_graphics_camera_simple_camera_setPosition (sdxgraphicsCameraSimpleCamera* self, Point2d* player) {
	Point2d _tmp0_ = {0};
	gdouble _tmp1_ = 0.0;
	gint _tmp2_ = 0;
	Vector2d _tmp3_ = {0};
	gdouble _tmp4_ = 0.0;
	Point2d _tmp5_ = {0};
	g_return_if_fail (self != NULL);
	g_return_if_fail (player != NULL);
	_tmp0_ = *player;
	_tmp1_ = _tmp0_.x;
	_tmp2_ = sdx_width;
	_tmp3_ = ((sdxgraphicsCamera*) self)->position;
	_tmp4_ = _tmp3_.y;
	_tmp5_.x = _tmp1_ - (((gdouble) _tmp2_) / 2);
	_tmp5_.y = _tmp4_;
	sdx_graphics_camera_setPosition ((sdxgraphicsCamera*) self, &_tmp5_);
}


static void sdx_graphics_camera_instance_init (sdxgraphicsCamera * self) {
	self->_retainCount = 1;
}


void sdx_graphics_camera_free (sdxgraphicsCamera* self) {
	g_slice_free (sdxgraphicsCamera, self);
}



