/* Surface.c generated by valac 0.34.8, the Vala compiler
 * generated from Surface.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <SDL2/SDL_surface.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL_image.h>
#include <SDL2/SDL_rwops.h>

typedef struct _sdxgraphicsSurface sdxgraphicsSurface;
#define _SDL_FreeSurface0(var) ((var == NULL) ? NULL : (var = (SDL_FreeSurface (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _sdxfilesFileHandle sdxfilesFileHandle;
#define _SDL_FreeRW0(var) ((var == NULL) ? NULL : (var = (SDL_FreeRW (var), NULL)))
void sdx_files_file_handle_release (sdxfilesFileHandle* self);
void sdx_files_file_handle_free (sdxfilesFileHandle* self);
sdxfilesFileHandle* sdx_files_file_handle_retain (sdxfilesFileHandle* self);
#define _sdx_files_file_handle_release0(var) ((var == NULL) ? NULL : (var = (sdx_files_file_handle_release (var), NULL)))

struct _sdxgraphicsSurface {
	gint _retainCount;
	SDL_Surface* surface;
	gint width;
	gint height;
	gint id;
	gchar* path;
};


extern gint sdx_graphics_surface_uniqueId;
gint sdx_graphics_surface_uniqueId = 0;

void sdx_graphics_surface_free (sdxgraphicsSurface* self);
static void sdx_graphics_surface_instance_init (sdxgraphicsSurface * self);
sdxgraphicsSurface* sdx_graphics_surface_retain (sdxgraphicsSurface* self);
void sdx_graphics_surface_release (sdxgraphicsSurface* self);
void sdx_graphics_surface_free (sdxgraphicsSurface* self);
sdxgraphicsSurface* sdx_graphics_surface_new (const gchar* path);
void sdx_files_file_handle_free (sdxfilesFileHandle* self);
sdxfilesFileHandle* sdx_files_asset (const gchar* path);
SDL_RWops* sdx_files_file_handle_getRWops (sdxfilesFileHandle* self);


sdxgraphicsSurface* sdx_graphics_surface_retain (sdxgraphicsSurface* self) {
	sdxgraphicsSurface* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_atomic_int_add ((volatile gint *) (&self->_retainCount), 1);
	result = self;
	return result;
}


void sdx_graphics_surface_release (sdxgraphicsSurface* self) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_atomic_int_dec_and_test ((volatile gint *) (&self->_retainCount));
	if (_tmp0_) {
		sdx_graphics_surface_free (self);
	}
}


sdxgraphicsSurface* sdx_graphics_surface_new (const gchar* path) {
	sdxgraphicsSurface* self;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	sdxfilesFileHandle* file = NULL;
	const gchar* _tmp2_ = NULL;
	sdxfilesFileHandle* _tmp3_ = NULL;
	SDL_RWops* _tmp4_ = NULL;
	SDL_RWops* _tmp5_ = NULL;
	SDL_Surface* _tmp6_ = NULL;
	SDL_Surface* _tmp7_ = NULL;
	gint _tmp8_ = 0;
	SDL_Surface* _tmp9_ = NULL;
	gint _tmp10_ = 0;
	g_return_val_if_fail (path != NULL, NULL);
	self = g_slice_new0 (sdxgraphicsSurface);
	sdx_graphics_surface_instance_init (self);
	_tmp0_ = path;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->path);
	self->path = _tmp1_;
	_tmp2_ = path;
	_tmp3_ = sdx_files_asset (_tmp2_);
	file = _tmp3_;
	_tmp4_ = sdx_files_file_handle_getRWops (file);
	_tmp5_ = _tmp4_;
	_tmp6_ = IMG_LoadPNG_RW (_tmp5_);
	_SDL_FreeSurface0 (self->surface);
	self->surface = _tmp6_;
	_SDL_FreeRW0 (_tmp5_);
	_tmp7_ = self->surface;
	_tmp8_ = _tmp7_->w;
	self->width = _tmp8_;
	_tmp9_ = self->surface;
	_tmp10_ = _tmp9_->h;
	self->height = _tmp10_;
	_sdx_files_file_handle_release0 (file);
	return self;
}


static void sdx_graphics_surface_instance_init (sdxgraphicsSurface * self) {
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	self->_retainCount = 1;
	_tmp0_ = sdx_graphics_surface_uniqueId;
	sdx_graphics_surface_uniqueId = _tmp0_ + 1;
	_tmp1_ = sdx_graphics_surface_uniqueId;
	self->id = _tmp1_;
}


void sdx_graphics_surface_free (sdxgraphicsSurface* self) {
	_SDL_FreeSurface0 (self->surface);
	_g_free0 (self->path);
	g_slice_free (sdxgraphicsSurface, self);
}



