/* TextureRegion.c generated by valac 0.34.8, the Vala compiler
 * generated from TextureRegion.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>

typedef struct _sdxgraphicsTextureRegion sdxgraphicsTextureRegion;
typedef struct _sdxgraphicsSurface sdxgraphicsSurface;
typedef sdxgraphicsSurface sdxgraphicsSurfaceTextureSurface;
void sdx_graphics_surface_release (sdxgraphicsSurface* self);
void sdx_graphics_surface_free (sdxgraphicsSurface* self);
sdxgraphicsSurface* sdx_graphics_surface_retain (sdxgraphicsSurface* self);
void sdx_graphics_surface_release (sdxgraphicsSurface* self);
void sdx_graphics_surface_free (sdxgraphicsSurface* self);
sdxgraphicsSurface* sdx_graphics_surface_retain (sdxgraphicsSurface* self);
#define _sdx_graphics_surface_release0(var) ((var == NULL) ? NULL : (var = (sdx_graphics_surface_release (var), NULL)))

struct _sdxgraphicsTextureRegion {
	gint _retainCount;
	sdxgraphicsSurfaceTextureSurface* texture;
	gint top;
	gint left;
	gint width;
	gint height;
	gint regionWidth;
	gint regionHeight;
	gdouble u;
	gdouble v;
	gdouble u2;
	gdouble v2;
};



void sdx_graphics_texture_region_free (sdxgraphicsTextureRegion* self);
void sdx_graphics_surface_free (sdxgraphicsSurface* self);
static void sdx_graphics_texture_region_instance_init (sdxgraphicsTextureRegion * self);
sdxgraphicsTextureRegion* sdx_graphics_texture_region_retain (sdxgraphicsTextureRegion* self);
void sdx_graphics_texture_region_release (sdxgraphicsTextureRegion* self);
void sdx_graphics_texture_region_free (sdxgraphicsTextureRegion* self);
sdxgraphicsTextureRegion* sdx_graphics_texture_region_new (sdxgraphicsSurfaceTextureSurface* texture, gint x, gint y, gint width, gint height);
gint sdx_graphics_surface_get_width (sdxgraphicsSurface* self);
gint sdx_graphics_surface_get_height (sdxgraphicsSurface* self);
void sdx_graphics_texture_region_setRegionXY (sdxgraphicsTextureRegion* self, gint x, gint y, gint width, gint height);
void sdx_graphics_texture_region_setRegion (sdxgraphicsTextureRegion* self, gdouble u, gdouble v, gdouble u2, gdouble v2);
void sdx_graphics_texture_region_setByRegion (sdxgraphicsTextureRegion* self, sdxgraphicsTextureRegion* region);
void sdx_graphics_texture_region_setByRegionXY (sdxgraphicsTextureRegion* self, sdxgraphicsTextureRegion* region, gint x, gint y, gint width, gint height);
gint sdx_graphics_texture_region_getRegionX (sdxgraphicsTextureRegion* self);
gint sdx_graphics_texture_region_getRegionY (sdxgraphicsTextureRegion* self);
void sdx_graphics_texture_region_flip (sdxgraphicsTextureRegion* self, gboolean x, gboolean y);
gdouble sdx_graphics_texture_region_getU (sdxgraphicsTextureRegion* self);
void sdx_graphics_texture_region_setU (sdxgraphicsTextureRegion* self, gdouble u);
gdouble sdx_graphics_texture_region_getV (sdxgraphicsTextureRegion* self);
void sdx_graphics_texture_region_setV (sdxgraphicsTextureRegion* self, gdouble v);
gdouble sdx_graphics_texture_region_getU2 (sdxgraphicsTextureRegion* self);
void sdx_graphics_texture_region_setU2 (sdxgraphicsTextureRegion* self, gdouble u2);
gdouble sdx_graphics_texture_region_getV2 (sdxgraphicsTextureRegion* self);
void sdx_graphics_texture_region_setV2 (sdxgraphicsTextureRegion* self, gdouble v2);
void sdx_graphics_texture_region_setRegionX (sdxgraphicsTextureRegion* self, gint x);
void sdx_graphics_texture_region_setRegionY (sdxgraphicsTextureRegion* self, gint y);
gint sdx_graphics_texture_region_getRegionWidth (sdxgraphicsTextureRegion* self);
void sdx_graphics_texture_region_setRegionWidth (sdxgraphicsTextureRegion* self, gint width);
gboolean sdx_graphics_texture_region_isFlipX (sdxgraphicsTextureRegion* self);
gint sdx_graphics_texture_region_getRegionHeight (sdxgraphicsTextureRegion* self);
void sdx_graphics_texture_region_setRegionHeight (sdxgraphicsTextureRegion* self, gint height);
gboolean sdx_graphics_texture_region_isFlipY (sdxgraphicsTextureRegion* self);


sdxgraphicsTextureRegion* sdx_graphics_texture_region_retain (sdxgraphicsTextureRegion* self) {
	sdxgraphicsTextureRegion* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_atomic_int_add ((volatile gint *) (&self->_retainCount), 1);
	result = self;
	return result;
}


void sdx_graphics_texture_region_release (sdxgraphicsTextureRegion* self) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_atomic_int_dec_and_test ((volatile gint *) (&self->_retainCount));
	if (_tmp0_) {
		sdx_graphics_texture_region_free (self);
	}
}


static gpointer _sdx_graphics_surface_retain0 (gpointer self) {
	return self ? sdx_graphics_surface_retain (self) : NULL;
}


sdxgraphicsTextureRegion* sdx_graphics_texture_region_new (sdxgraphicsSurfaceTextureSurface* texture, gint x, gint y, gint width, gint height) {
	sdxgraphicsTextureRegion* self;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	sdxgraphicsSurfaceTextureSurface* _tmp12_ = NULL;
	sdxgraphicsSurfaceTextureSurface* _tmp13_ = NULL;
	gint _tmp14_ = 0;
	gint _tmp15_ = 0;
	gint _tmp16_ = 0;
	gint _tmp17_ = 0;
	gint _tmp18_ = 0;
	gint _tmp19_ = 0;
	gint _tmp20_ = 0;
	gint _tmp21_ = 0;
	g_return_val_if_fail (texture != NULL, NULL);
	self = g_slice_new0 (sdxgraphicsTextureRegion);
	sdx_graphics_texture_region_instance_init (self);
	_tmp1_ = width;
	if (_tmp1_ == 0) {
		sdxgraphicsSurfaceTextureSurface* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		_tmp2_ = texture;
		_tmp3_ = sdx_graphics_surface_get_width ((sdxgraphicsSurface*) _tmp2_);
		_tmp4_ = _tmp3_;
		_tmp0_ = _tmp4_;
	} else {
		gint _tmp5_ = 0;
		_tmp5_ = width;
		_tmp0_ = _tmp5_;
	}
	width = _tmp0_;
	_tmp7_ = height;
	if (_tmp7_ == 0) {
		sdxgraphicsSurfaceTextureSurface* _tmp8_ = NULL;
		gint _tmp9_ = 0;
		gint _tmp10_ = 0;
		_tmp8_ = texture;
		_tmp9_ = sdx_graphics_surface_get_height ((sdxgraphicsSurface*) _tmp8_);
		_tmp10_ = _tmp9_;
		_tmp6_ = _tmp10_;
	} else {
		gint _tmp11_ = 0;
		_tmp11_ = height;
		_tmp6_ = _tmp11_;
	}
	height = _tmp6_;
	_tmp12_ = texture;
	_tmp13_ = _sdx_graphics_surface_retain0 (_tmp12_);
	_sdx_graphics_surface_release0 (self->texture);
	self->texture = _tmp13_;
	_tmp14_ = x;
	self->top = _tmp14_;
	_tmp15_ = y;
	self->left = _tmp15_;
	_tmp16_ = width;
	self->width = _tmp16_;
	_tmp17_ = height;
	self->height = _tmp17_;
	_tmp18_ = x;
	_tmp19_ = y;
	_tmp20_ = width;
	_tmp21_ = height;
	sdx_graphics_texture_region_setRegionXY (self, _tmp18_, _tmp19_, _tmp20_, _tmp21_);
	return self;
}


void sdx_graphics_texture_region_setRegion (sdxgraphicsTextureRegion* self, gdouble u, gdouble v, gdouble u2, gdouble v2) {
	gint texWidth = 0;
	gint _tmp0_ = 0;
	gint texHeight = 0;
	gint _tmp1_ = 0;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp3_ = 0.0;
	gdouble _tmp4_ = 0.0;
	gint _tmp5_ = 0;
	gdouble _tmp6_ = 0.0;
	gdouble _tmp7_ = 0.0;
	gdouble _tmp8_ = 0.0;
	gdouble _tmp9_ = 0.0;
	gint _tmp10_ = 0;
	gdouble _tmp11_ = 0.0;
	gboolean _tmp12_ = FALSE;
	gint _tmp13_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->width;
	texWidth = _tmp0_;
	_tmp1_ = self->height;
	texHeight = _tmp1_;
	_tmp2_ = u2;
	_tmp3_ = u;
	_tmp4_ = fabs (_tmp2_ - _tmp3_);
	_tmp5_ = texWidth;
	_tmp6_ = round (_tmp4_ * _tmp5_);
	self->regionWidth = (gint) _tmp6_;
	_tmp7_ = v2;
	_tmp8_ = v;
	_tmp9_ = fabs (_tmp7_ - _tmp8_);
	_tmp10_ = texHeight;
	_tmp11_ = round (_tmp9_ * _tmp10_);
	self->regionHeight = (gint) _tmp11_;
	_tmp13_ = self->regionWidth;
	if (_tmp13_ == 1) {
		gint _tmp14_ = 0;
		_tmp14_ = self->regionHeight;
		_tmp12_ = _tmp14_ == 1;
	} else {
		_tmp12_ = FALSE;
	}
	if (_tmp12_) {
		gdouble adjustX = 0.0;
		gint _tmp15_ = 0;
		gdouble _tmp16_ = 0.0;
		gdouble _tmp17_ = 0.0;
		gdouble adjustY = 0.0;
		gint _tmp18_ = 0;
		gdouble _tmp19_ = 0.0;
		gdouble _tmp20_ = 0.0;
		_tmp15_ = texWidth;
		adjustX = 0.25 / _tmp15_;
		_tmp16_ = adjustX;
		u = _tmp16_;
		_tmp17_ = adjustX;
		u2 = _tmp17_;
		_tmp18_ = texHeight;
		adjustY = 0.25 / _tmp18_;
		_tmp19_ = adjustY;
		v = _tmp19_;
		_tmp20_ = adjustY;
		v2 = _tmp20_;
	}
}


void sdx_graphics_texture_region_setRegionXY (sdxgraphicsTextureRegion* self, gint x, gint y, gint width, gint height) {
	gint invTexWidth = 0;
	gint _tmp0_ = 0;
	gint invTexHeight = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	gdouble _tmp9_ = 0.0;
	gint _tmp10_ = 0;
	gdouble _tmp11_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->width;
	invTexWidth = 1 / _tmp0_;
	_tmp1_ = self->height;
	invTexHeight = 1 / _tmp1_;
	_tmp2_ = x;
	_tmp3_ = y;
	_tmp4_ = x;
	_tmp5_ = width;
	_tmp6_ = y;
	_tmp7_ = height;
	sdx_graphics_texture_region_setRegion (self, (gdouble) (_tmp2_ * invTexWidth), (gdouble) (_tmp3_ * invTexHeight), (gdouble) ((_tmp4_ + _tmp5_) * invTexWidth), (gdouble) ((_tmp6_ + _tmp7_) * invTexHeight));
	_tmp8_ = width;
	_tmp9_ = fabs ((gdouble) _tmp8_);
	self->regionWidth = (gint) _tmp9_;
	_tmp10_ = height;
	_tmp11_ = fabs ((gdouble) _tmp10_);
	self->regionHeight = (gint) _tmp11_;
}


void sdx_graphics_texture_region_setByRegion (sdxgraphicsTextureRegion* self, sdxgraphicsTextureRegion* region) {
	sdxgraphicsTextureRegion* _tmp0_ = NULL;
	sdxgraphicsSurfaceTextureSurface* _tmp1_ = NULL;
	sdxgraphicsSurfaceTextureSurface* _tmp2_ = NULL;
	sdxgraphicsTextureRegion* _tmp3_ = NULL;
	gdouble _tmp4_ = 0.0;
	sdxgraphicsTextureRegion* _tmp5_ = NULL;
	gdouble _tmp6_ = 0.0;
	sdxgraphicsTextureRegion* _tmp7_ = NULL;
	gdouble _tmp8_ = 0.0;
	sdxgraphicsTextureRegion* _tmp9_ = NULL;
	gdouble _tmp10_ = 0.0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (region != NULL);
	_tmp0_ = region;
	_tmp1_ = _tmp0_->texture;
	_tmp2_ = _sdx_graphics_surface_retain0 (_tmp1_);
	_sdx_graphics_surface_release0 (self->texture);
	self->texture = _tmp2_;
	_tmp3_ = region;
	_tmp4_ = _tmp3_->u;
	_tmp5_ = region;
	_tmp6_ = _tmp5_->v;
	_tmp7_ = region;
	_tmp8_ = _tmp7_->u2;
	_tmp9_ = region;
	_tmp10_ = _tmp9_->v2;
	sdx_graphics_texture_region_setRegion (self, _tmp4_, _tmp6_, _tmp8_, _tmp10_);
}


void sdx_graphics_texture_region_setByRegionXY (sdxgraphicsTextureRegion* self, sdxgraphicsTextureRegion* region, gint x, gint y, gint width, gint height) {
	sdxgraphicsTextureRegion* _tmp0_ = NULL;
	sdxgraphicsSurfaceTextureSurface* _tmp1_ = NULL;
	sdxgraphicsSurfaceTextureSurface* _tmp2_ = NULL;
	sdxgraphicsTextureRegion* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	sdxgraphicsTextureRegion* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	gint _tmp9_ = 0;
	gint _tmp10_ = 0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (region != NULL);
	_tmp0_ = region;
	_tmp1_ = _tmp0_->texture;
	_tmp2_ = _sdx_graphics_surface_retain0 (_tmp1_);
	_sdx_graphics_surface_release0 (self->texture);
	self->texture = _tmp2_;
	_tmp3_ = region;
	_tmp4_ = sdx_graphics_texture_region_getRegionX (_tmp3_);
	_tmp5_ = x;
	_tmp6_ = region;
	_tmp7_ = sdx_graphics_texture_region_getRegionY (_tmp6_);
	_tmp8_ = y;
	_tmp9_ = width;
	_tmp10_ = height;
	sdx_graphics_texture_region_setRegionXY (self, _tmp4_ + _tmp5_, _tmp7_ + _tmp8_, _tmp9_, _tmp10_);
}


void sdx_graphics_texture_region_flip (sdxgraphicsTextureRegion* self, gboolean x, gboolean y) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp4_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = x;
	if (_tmp0_) {
		gdouble temp = 0.0;
		gdouble _tmp1_ = 0.0;
		gdouble _tmp2_ = 0.0;
		gdouble _tmp3_ = 0.0;
		_tmp1_ = self->u;
		temp = _tmp1_;
		_tmp2_ = self->u2;
		self->u = _tmp2_;
		_tmp3_ = temp;
		self->u2 = _tmp3_;
	}
	_tmp4_ = y;
	if (_tmp4_) {
		gdouble temp = 0.0;
		gdouble _tmp5_ = 0.0;
		gdouble _tmp6_ = 0.0;
		gdouble _tmp7_ = 0.0;
		_tmp5_ = self->v;
		temp = _tmp5_;
		_tmp6_ = self->v2;
		self->v = _tmp6_;
		_tmp7_ = temp;
		self->v2 = _tmp7_;
	}
}


gdouble sdx_graphics_texture_region_getU (sdxgraphicsTextureRegion* self) {
	gdouble result = 0.0;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->u;
	result = _tmp0_;
	return result;
}


void sdx_graphics_texture_region_setU (sdxgraphicsTextureRegion* self, gdouble u) {
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp3_ = 0.0;
	gint _tmp4_ = 0;
	gdouble _tmp5_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = u;
	self->u = _tmp0_;
	_tmp1_ = self->u2;
	_tmp2_ = u;
	_tmp3_ = fabs (_tmp1_ - _tmp2_);
	_tmp4_ = self->width;
	_tmp5_ = round (_tmp3_ * _tmp4_);
	self->regionWidth = (gint) _tmp5_;
}


gdouble sdx_graphics_texture_region_getV (sdxgraphicsTextureRegion* self) {
	gdouble result = 0.0;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->v;
	result = _tmp0_;
	return result;
}


void sdx_graphics_texture_region_setV (sdxgraphicsTextureRegion* self, gdouble v) {
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp3_ = 0.0;
	gint _tmp4_ = 0;
	gdouble _tmp5_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = v;
	self->v = _tmp0_;
	_tmp1_ = self->v2;
	_tmp2_ = v;
	_tmp3_ = fabs (_tmp1_ - _tmp2_);
	_tmp4_ = self->height;
	_tmp5_ = round (_tmp3_ * _tmp4_);
	self->regionHeight = (gint) _tmp5_;
}


gdouble sdx_graphics_texture_region_getU2 (sdxgraphicsTextureRegion* self) {
	gdouble result = 0.0;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->u2;
	result = _tmp0_;
	return result;
}


void sdx_graphics_texture_region_setU2 (sdxgraphicsTextureRegion* self, gdouble u2) {
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp3_ = 0.0;
	gint _tmp4_ = 0;
	gdouble _tmp5_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = u2;
	self->u2 = _tmp0_;
	_tmp1_ = u2;
	_tmp2_ = self->u;
	_tmp3_ = fabs (_tmp1_ - _tmp2_);
	_tmp4_ = self->width;
	_tmp5_ = round (_tmp3_ * _tmp4_);
	self->regionWidth = (gint) _tmp5_;
}


gdouble sdx_graphics_texture_region_getV2 (sdxgraphicsTextureRegion* self) {
	gdouble result = 0.0;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->v2;
	result = _tmp0_;
	return result;
}


void sdx_graphics_texture_region_setV2 (sdxgraphicsTextureRegion* self, gdouble v2) {
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp3_ = 0.0;
	gint _tmp4_ = 0;
	gdouble _tmp5_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = v2;
	self->v2 = _tmp0_;
	_tmp1_ = v2;
	_tmp2_ = self->v;
	_tmp3_ = fabs (_tmp1_ - _tmp2_);
	_tmp4_ = self->height;
	_tmp5_ = round (_tmp3_ * _tmp4_);
	self->regionHeight = (gint) _tmp5_;
}


gint sdx_graphics_texture_region_getRegionX (sdxgraphicsTextureRegion* self) {
	gint result = 0;
	gdouble _tmp0_ = 0.0;
	gint _tmp1_ = 0;
	gdouble _tmp2_ = 0.0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->u;
	_tmp1_ = self->width;
	_tmp2_ = round (_tmp0_ * _tmp1_);
	result = (gint) _tmp2_;
	return result;
}


void sdx_graphics_texture_region_setRegionX (sdxgraphicsTextureRegion* self, gint x) {
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = x;
	_tmp1_ = self->width;
	sdx_graphics_texture_region_setU (self, _tmp0_ / ((gdouble) _tmp1_));
}


gint sdx_graphics_texture_region_getRegionY (sdxgraphicsTextureRegion* self) {
	gint result = 0;
	gdouble _tmp0_ = 0.0;
	gint _tmp1_ = 0;
	gdouble _tmp2_ = 0.0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->v;
	_tmp1_ = self->height;
	_tmp2_ = round (_tmp0_ * _tmp1_);
	result = (gint) _tmp2_;
	return result;
}


void sdx_graphics_texture_region_setRegionY (sdxgraphicsTextureRegion* self, gint y) {
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = y;
	_tmp1_ = self->height;
	sdx_graphics_texture_region_setV (self, (gdouble) (_tmp0_ / _tmp1_));
}


/** Returns the region's width. */
gint sdx_graphics_texture_region_getRegionWidth (sdxgraphicsTextureRegion* self) {
	gint result = 0;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->regionWidth;
	result = _tmp0_;
	return result;
}


void sdx_graphics_texture_region_setRegionWidth (sdxgraphicsTextureRegion* self, gint width) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = sdx_graphics_texture_region_isFlipX (self);
	if (_tmp0_) {
		gdouble _tmp1_ = 0.0;
		gint _tmp2_ = 0;
		gint _tmp3_ = 0;
		_tmp1_ = self->u2;
		_tmp2_ = width;
		_tmp3_ = self->width;
		sdx_graphics_texture_region_setU (self, _tmp1_ + (_tmp2_ / ((gdouble) _tmp3_)));
	} else {
		gdouble _tmp4_ = 0.0;
		gint _tmp5_ = 0;
		gint _tmp6_ = 0;
		_tmp4_ = self->u;
		_tmp5_ = width;
		_tmp6_ = self->width;
		sdx_graphics_texture_region_setU2 (self, _tmp4_ + (_tmp5_ / ((gdouble) _tmp6_)));
	}
}


/** Returns the region's height. */
gint sdx_graphics_texture_region_getRegionHeight (sdxgraphicsTextureRegion* self) {
	gint result = 0;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->regionHeight;
	result = _tmp0_;
	return result;
}


void sdx_graphics_texture_region_setRegionHeight (sdxgraphicsTextureRegion* self, gint height) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = sdx_graphics_texture_region_isFlipY (self);
	if (_tmp0_) {
		gdouble _tmp1_ = 0.0;
		gint _tmp2_ = 0;
		gint _tmp3_ = 0;
		_tmp1_ = self->v2;
		_tmp2_ = height;
		_tmp3_ = self->height;
		sdx_graphics_texture_region_setV (self, _tmp1_ + (_tmp2_ / ((gdouble) _tmp3_)));
	} else {
		gdouble _tmp4_ = 0.0;
		gint _tmp5_ = 0;
		gint _tmp6_ = 0;
		_tmp4_ = self->v;
		_tmp5_ = height;
		_tmp6_ = self->height;
		sdx_graphics_texture_region_setV2 (self, _tmp4_ + (_tmp5_ / ((gdouble) _tmp6_)));
	}
}


gboolean sdx_graphics_texture_region_isFlipX (sdxgraphicsTextureRegion* self) {
	gboolean result = FALSE;
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->u;
	_tmp1_ = self->u2;
	result = _tmp0_ > _tmp1_;
	return result;
}


gboolean sdx_graphics_texture_region_isFlipY (sdxgraphicsTextureRegion* self) {
	gboolean result = FALSE;
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->v;
	_tmp1_ = self->v2;
	result = _tmp0_ > _tmp1_;
	return result;
}


static void sdx_graphics_texture_region_instance_init (sdxgraphicsTextureRegion * self) {
	self->_retainCount = 1;
}


void sdx_graphics_texture_region_free (sdxgraphicsTextureRegion* self) {
	_sdx_graphics_surface_release0 (self->texture);
	g_slice_free (sdxgraphicsTextureRegion, self);
}



