/* TextureAtlas.c generated by valac 0.34.8, the Vala compiler
 * generated from TextureAtlas.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>

typedef struct _sdxgraphicsTextureAtlas sdxgraphicsTextureAtlas;
typedef struct _sdxgraphicsTextureAtlasInnerClass sdxgraphicsTextureAtlasInnerClass;
void sdx_graphics_texture_atlas_innerclass_release (sdxgraphicsTextureAtlasInnerClass* self);
void sdx_graphics_texture_atlas_innerclass_free (sdxgraphicsTextureAtlasInnerClass* self);
sdxgraphicsTextureAtlasInnerClass* sdx_graphics_texture_atlas_innerclass_retain (sdxgraphicsTextureAtlasInnerClass* self);
#define _sdx_graphics_texture_atlas_innerclass_release0(var) ((var == NULL) ? NULL : (var = (sdx_graphics_texture_atlas_innerclass_release (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _sdxgraphicsTextureAtlas {
	gint _retainCount;
	sdxgraphicsTextureAtlasInnerClass* x;
};

struct _sdxgraphicsTextureAtlasInnerClass {
	gint _retainCount;
	gchar* name;
};



void sdx_graphics_texture_atlas_free (sdxgraphicsTextureAtlas* self);
void sdx_graphics_texture_atlas_innerclass_free (sdxgraphicsTextureAtlasInnerClass* self);
static void sdx_graphics_texture_atlas_instance_init (sdxgraphicsTextureAtlas * self);
sdxgraphicsTextureAtlas* sdx_graphics_texture_atlas_retain (sdxgraphicsTextureAtlas* self);
void sdx_graphics_texture_atlas_release (sdxgraphicsTextureAtlas* self);
void sdx_graphics_texture_atlas_free (sdxgraphicsTextureAtlas* self);
sdxgraphicsTextureAtlas* sdx_graphics_texture_atlas_new (void);
sdxgraphicsTextureAtlasInnerClass* sdx_graphics_texture_atlas_innerclass_new (void);
sdxgraphicsTextureAtlasInnerClass* sdx_graphics_texture_atlas_createInner (sdxgraphicsTextureAtlas* self);
static void sdx_graphics_texture_atlas_innerclass_instance_init (sdxgraphicsTextureAtlasInnerClass * self);
sdxgraphicsTextureAtlasInnerClass* sdx_graphics_texture_atlas_innerclass_retain (sdxgraphicsTextureAtlasInnerClass* self);
void sdx_graphics_texture_atlas_innerclass_release (sdxgraphicsTextureAtlasInnerClass* self);
void sdx_graphics_texture_atlas_innerclass_free (sdxgraphicsTextureAtlasInnerClass* self);


sdxgraphicsTextureAtlas* sdx_graphics_texture_atlas_retain (sdxgraphicsTextureAtlas* self) {
	sdxgraphicsTextureAtlas* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_atomic_int_add ((volatile gint *) (&self->_retainCount), 1);
	result = self;
	return result;
}


void sdx_graphics_texture_atlas_release (sdxgraphicsTextureAtlas* self) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_atomic_int_dec_and_test ((volatile gint *) (&self->_retainCount));
	if (_tmp0_) {
		sdx_graphics_texture_atlas_free (self);
	}
}


sdxgraphicsTextureAtlas* sdx_graphics_texture_atlas_new (void) {
	sdxgraphicsTextureAtlas* self;
	sdxgraphicsTextureAtlasInnerClass* _tmp0_ = NULL;
	self = g_slice_new0 (sdxgraphicsTextureAtlas);
	sdx_graphics_texture_atlas_instance_init (self);
	_tmp0_ = sdx_graphics_texture_atlas_innerclass_new ();
	_sdx_graphics_texture_atlas_innerclass_release0 (self->x);
	self->x = _tmp0_;
	g_print ("this is a test\n");
	return self;
}


sdxgraphicsTextureAtlasInnerClass* sdx_graphics_texture_atlas_createInner (sdxgraphicsTextureAtlas* self) {
	sdxgraphicsTextureAtlasInnerClass* result = NULL;
	sdxgraphicsTextureAtlasInnerClass* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = sdx_graphics_texture_atlas_innerclass_new ();
	result = _tmp0_;
	return result;
}


sdxgraphicsTextureAtlasInnerClass* sdx_graphics_texture_atlas_innerclass_retain (sdxgraphicsTextureAtlasInnerClass* self) {
	sdxgraphicsTextureAtlasInnerClass* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_atomic_int_add ((volatile gint *) (&self->_retainCount), 1);
	result = self;
	return result;
}


void sdx_graphics_texture_atlas_innerclass_release (sdxgraphicsTextureAtlasInnerClass* self) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_atomic_int_dec_and_test ((volatile gint *) (&self->_retainCount));
	if (_tmp0_) {
		sdx_graphics_texture_atlas_innerclass_free (self);
	}
}


sdxgraphicsTextureAtlasInnerClass* sdx_graphics_texture_atlas_innerclass_new (void) {
	sdxgraphicsTextureAtlasInnerClass* self;
	gchar* _tmp0_ = NULL;
	self = g_slice_new0 (sdxgraphicsTextureAtlasInnerClass);
	sdx_graphics_texture_atlas_innerclass_instance_init (self);
	g_print ("this is na inner test\n");
	_tmp0_ = g_strdup ("frodo");
	_g_free0 (self->name);
	self->name = _tmp0_;
	return self;
}


static void sdx_graphics_texture_atlas_innerclass_instance_init (sdxgraphicsTextureAtlasInnerClass * self) {
	self->_retainCount = 1;
}


void sdx_graphics_texture_atlas_innerclass_free (sdxgraphicsTextureAtlasInnerClass* self) {
	_g_free0 (self->name);
	g_slice_free (sdxgraphicsTextureAtlasInnerClass, self);
}


static void sdx_graphics_texture_atlas_instance_init (sdxgraphicsTextureAtlas * self) {
	self->_retainCount = 1;
}


void sdx_graphics_texture_atlas_free (sdxgraphicsTextureAtlas* self) {
	_sdx_graphics_texture_atlas_innerclass_release0 (self->x);
	g_slice_free (sdxgraphicsTextureAtlas, self);
}



