/* files.c generated by valac 0.34.8, the Vala compiler
 * generated from files.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define SDX_TYPE_FILE_TYPE (sdx_file_type_get_type ())
typedef struct _sdxfilesFileHandle sdxfilesFileHandle;

typedef enum  {
	SDX_FILE_TYPE_Parent,
	SDX_FILE_TYPE_Resource,
	SDX_FILE_TYPE_Asset,
	SDX_FILE_TYPE_Absolute,
	SDX_FILE_TYPE_Relative
} sdxFileType;



GType sdx_file_type_get_type (void) G_GNUC_CONST;
void sdx_files_file_handle_free (sdxfilesFileHandle* self);
sdxfilesFileHandle* sdx_files_getHandle (const gchar* path, sdxFileType type);
sdxfilesFileHandle* sdx_files_file_handle_new (const gchar* path, sdxFileType type);
sdxfilesFileHandle* sdx_files_resource (const gchar* path);
sdxfilesFileHandle* sdx_files_asset (const gchar* path);
sdxfilesFileHandle* sdx_files_absolute (const gchar* path);
sdxfilesFileHandle* sdx_files_relative (const gchar* path);


sdxfilesFileHandle* sdx_files_getHandle (const gchar* path, sdxFileType type) {
	sdxfilesFileHandle* result = NULL;
	const gchar* _tmp0_ = NULL;
	sdxFileType _tmp1_ = 0;
	sdxfilesFileHandle* _tmp2_ = NULL;
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = path;
	_tmp1_ = type;
	_tmp2_ = sdx_files_file_handle_new (_tmp0_, _tmp1_);
	result = _tmp2_;
	return result;
}


sdxfilesFileHandle* sdx_files_resource (const gchar* path) {
	sdxfilesFileHandle* result = NULL;
	const gchar* _tmp0_ = NULL;
	sdxfilesFileHandle* _tmp1_ = NULL;
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = path;
	_tmp1_ = sdx_files_file_handle_new (_tmp0_, SDX_FILE_TYPE_Resource);
	result = _tmp1_;
	return result;
}


sdxfilesFileHandle* sdx_files_asset (const gchar* path) {
	sdxfilesFileHandle* result = NULL;
	const gchar* _tmp0_ = NULL;
	sdxfilesFileHandle* _tmp1_ = NULL;
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = path;
	_tmp1_ = sdx_files_file_handle_new (_tmp0_, SDX_FILE_TYPE_Asset);
	result = _tmp1_;
	return result;
}


sdxfilesFileHandle* sdx_files_absolute (const gchar* path) {
	sdxfilesFileHandle* result = NULL;
	const gchar* _tmp0_ = NULL;
	sdxfilesFileHandle* _tmp1_ = NULL;
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = path;
	_tmp1_ = sdx_files_file_handle_new (_tmp0_, SDX_FILE_TYPE_Absolute);
	result = _tmp1_;
	return result;
}


sdxfilesFileHandle* sdx_files_relative (const gchar* path) {
	sdxfilesFileHandle* result = NULL;
	const gchar* _tmp0_ = NULL;
	sdxfilesFileHandle* _tmp1_ = NULL;
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = path;
	_tmp1_ = sdx_files_file_handle_new (_tmp0_, SDX_FILE_TYPE_Relative);
	result = _tmp1_;
	return result;
}



